import { GENRE_CATEGORIES } from './genres.js';
import TILE_GENRES from './genreTiles.manifest.json' with { type: 'json' };

// Category labels carry a leading emoji in the data; the neon restyle shows none.
export const plainLabel = (label) => label.replace(/^[^\p{L}\p{N}]+/u, '').trim();

// The category chip the genre grid opens on: the first one holding a selected
// (e.g. prefilled) genre, so a pre-picked choice is visible straight away.
export function initialCategory(selGenres) {
  const withSel = GENRE_CATEGORIES.find((c) => c.genres.some((g) => selGenres.has(g)));
  return (withSel || GENRE_CATEGORIES[0]).id;
}

// Static tile artwork (public/images/genres/<genre>.webp, generated by
// scripts/generate_genre_tiles.py). Only genres listed in the manifest have a
// file, so a missing image is never requested — those tiles keep the gradient.
const AVAILABLE = new Set(TILE_GENRES);
export function tileArt(genre) {
  return AVAILABLE.has(genre) ? `/images/genres/${genre}.webp` : null;
}
