import { BeatsNavbar } from '../components/BeatsNavbar';

export default function TermsPage() {
  return (
    <div className="content-page-wrap">
      <BeatsNavbar />
      <div className="hero-orbs" aria-hidden>
        <div className="orb orb-1" style={{ opacity: 0.3 }} />
      </div>
      <main className="content-page page">
        <h1 className="content-title">Terms &amp; Conditions</h1>
        <p className="content-meta">Last updated: 28 May 2026</p>

        <section className="content-section">
          <h2>1. Acceptance of Terms</h2>
          <p>
            By accessing or using Zeus Beats ("the Service"), you agree to be bound by these
            Terms &amp; Conditions ("Terms"). If you do not agree to these Terms, you must not use
            the Service. These Terms constitute a legally binding agreement between you and Zeus
            Beats Ltd (company number 17230535) ("we", "us",
            "our"), a company registered in England and Wales. We reserve the right to update these
            Terms at any time. Continued use of the Service after changes constitutes acceptance of
            the updated Terms.
          </p>
        </section>

        <section className="content-section">
          <h2>2. Service Description</h2>
          <p>
            Zeus Beats is an AI-powered SaaS platform designed to help musicians, content creators,
            and businesses with tasks including: AI music generation, cover art creation, avatar
            lip-sync videos, YouTube uploads, and automated social media posting.
          </p>
          <p>
            The Service is provided "as is" and we make no warranties that outputs will be
            error-free, complete, or suitable for any particular purpose. AI-generated content
            should always be reviewed before use in commercial or client-facing work. Zeus Beats
            does not provide legal, financial, tax, or professional advice, and nothing in the
            Service should be construed as such.
          </p>
        </section>

        <section className="content-section">
          <h2>3. AI-Powered Service &amp; Third-Party Disclaimer</h2>
          <p>
            Zeus Beats uses third-party AI systems to generate music, lyrics, cover art, and
            videos. By using the Service, you acknowledge and agree to the following:
          </p>
          <ul>
            <li>
              <strong>AI-generated outputs:</strong> All music, lyrics, images, and videos
              produced by Zeus Beats are generated by artificial intelligence. They may contain
              errors, inaccuracies, or unintended content. You are solely responsible for
              reviewing the suitability of any AI-generated output before use.
            </li>
            <li>
              <strong>Content processing:</strong> Your prompts and requests are transmitted to
              and processed by third-party AI systems in order to generate outputs. By using the
              Service, you consent to your inputs being processed by our AI providers.
            </li>
            <li>
              <strong>No sensitive data in prompts:</strong> You should not include sensitive
              personal data, financial information, passwords, or confidential third-party
              information in your prompts.
            </li>
            <li>
              <strong>No guarantee of accuracy:</strong> We make no warranty that AI outputs
              are accurate, current, or complete. Zeus Beats expressly disclaims liability
              for any reliance placed on AI-generated content.
            </li>
          </ul>
        </section>

        <section className="content-section">
          <h2>4. Account Registration</h2>
          <p>
            To access the full Service, you must create an account by providing accurate and
            complete information. You are responsible for:
          </p>
          <ul>
            <li>Maintaining the confidentiality of your password and account credentials</li>
            <li>All activity that occurs under your account</li>
            <li>Notifying us immediately of any unauthorised use of your account</li>
            <li>Ensuring all registration information is kept accurate and up to date</li>
          </ul>
          <p>
            You must be at least 18 years of age to create an account. By registering, you
            confirm that you meet this requirement and that you are not prohibited from using the
            Service under any applicable law.
          </p>
        </section>

        <section className="content-section">
          <h2>5. Payment Terms &amp; Subscriptions</h2>
          <p>
            Zeus Beats offers a free tier and paid subscription plans (Music Starter at £9/month,
            Music Pro at £19/month, and Music Agency at £39/month). All prices are shown in
            British Pounds (GBP) and are inclusive of VAT where applicable.
          </p>
          <p>
            Paid subscriptions are billed monthly in advance on your subscription anniversary
            date. By subscribing, you authorise us to charge your payment method on a recurring
            basis until you cancel. Payment is processed by Stripe; we do not store your full
            card details. Your payment information is subject to{' '}
            <a
              href="https://stripe.com/privacy"
              target="_blank"
              rel="noopener noreferrer"
              className="auth-link"
            >
              Stripe's Privacy Policy
            </a>.
          </p>
          <p>
            We reserve the right to change subscription prices with 30 days' written notice via
            email. Price changes will not affect your current billing period.
          </p>
        </section>

        <section className="content-section">
          <h2>6. Refund Policy</h2>
          <p>
            We offer a <strong>7-day refund window</strong> from the date of your initial
            subscription payment. If you are not satisfied with the Service, you may request a
            full refund within 7 days of your first payment by contacting us at{' '}
            <a href="mailto:hello@zeusbeats.com" className="auth-link">hello@zeusbeats.com</a>.
          </p>
          <p>
            <strong>After 7 days, no refunds will be issued</strong> for any subscription fees
            already paid, including in the event of cancellation, suspension, or termination of
            your account. This applies to both monthly subscription fees and any one-time charges.
          </p>
          <p>
            Refunds are not available for:
          </p>
          <ul>
            <li>Partial months of subscription after cancellation</li>
            <li>Accounts suspended or terminated for breach of these Terms</li>
            <li>Renewed subscription periods after the initial 7-day window has passed</li>
          </ul>
          <p>
            Nothing in this refund policy affects your statutory rights under the Consumer Rights
            Act 2015 or any other applicable UK consumer protection legislation.
          </p>
        </section>

        <section className="content-section">
          <h2>7. Cancellation Policy</h2>
          <p>
            You may cancel your subscription at any time through the Billing section of your
            account or by contacting us at{' '}
            <a href="mailto:hello@zeusbeats.com" className="auth-link">hello@zeusbeats.com</a>.
          </p>
          <p>
            Upon cancellation:
          </p>
          <ul>
            <li>
              Your subscription will remain active until the end of the current billing period
            </li>
            <li>
              You will not be charged for the next billing period
            </li>
            <li>
              Your account will revert to the free tier at the end of the paid period
            </li>
            <li>
              No partial-month refunds are issued for early cancellation (except within the
              7-day refund window described above)
            </li>
          </ul>
          <p>
            We reserve the right to cancel or suspend your account immediately for breach of
            these Terms, without notice and without refund.
          </p>
        </section>

        <section className="content-section">
          <h2>8. Acceptable Use</h2>
          <p>You agree not to use the Service to:</p>
          <ul>
            <li>Generate, distribute, or store illegal content of any kind</li>
            <li>Infringe upon the intellectual property rights of any third party</li>
            <li>Create content intended to deceive, harass, threaten, or harm any individual</li>
            <li>Attempt to reverse-engineer or extract the underlying AI models</li>
            <li>Resell or sublicense access to the Service without our written consent</li>
            <li>Use automated scripts or bots to access the Service beyond normal usage</li>
            <li>Upload or transmit content that violates any applicable law or regulation</li>
            <li>Circumvent usage limits, access controls, or subscription restrictions</li>
          </ul>
          <p>
            We reserve the right to suspend or terminate accounts that violate these acceptable
            use policies, without notice and without refund.
          </p>
        </section>

        <section className="content-section">
          <h2>9. Intellectual Property</h2>
          <p>
            <strong>Our IP:</strong> The Zeus Beats platform, its software, design, branding,
            and underlying technology are owned by us and protected by copyright, trademark, and
            other intellectual property laws. You may not copy, modify, distribute, or create
            derivative works from our platform without express written permission.
          </p>
          <p>
            <strong>Your content:</strong> You retain ownership of any content you submit to the
            Service (your prompts, uploaded files, and generated songs). By using the Service, you
            grant us a limited, non-exclusive, royalty-free licence to process your content
            solely for the purpose of delivering the Service.
          </p>
          <p>
            <strong>AI-generated outputs:</strong> Music, lyrics, images, and videos generated by
            Zeus Beats in response to your prompts are provided for your use. You are responsible
            for ensuring that AI-generated outputs do not infringe third-party intellectual
            property rights before any commercial use.
          </p>
        </section>

        <section className="content-section">
          <h2>10. Music Ownership &amp; Commercial Rights</h2>
          <p>
            All music, lyrics, cover art, and videos generated through Zeus Beats using your
            prompts are yours — you own the output. This section sets out what you may do with
            that output depending on your plan.
          </p>

          <p><strong>Free plan — personal use only</strong></p>
          <ul>
            <li>
              Songs generated on the Free plan may be used for personal, non-commercial purposes
              only (private listening, sharing with friends, personal creative projects).
            </li>
            <li>
              You may <strong>not</strong> use Free plan songs for any commercial purpose,
              including selling, licensing, sync placements, advertising, brand use, or monetised
              distribution on any platform (YouTube monetisation, Spotify, Apple Music, etc.).
            </li>
            <li>
              Upgrading to a paid plan does not retroactively grant commercial rights to songs
              generated while on the Free plan.
            </li>
          </ul>

          <p><strong>Paid plans — full commercial rights</strong></p>
          <ul>
            <li>
              Subscribers on Music Starter (£9/month), Music Pro (£19/month), and Music Agency
              (£39/month) receive <strong>full commercial rights</strong> to all songs generated
              during their active subscription period.
            </li>
            <li>
              You may sell, license, sync, broadcast, stream, monetise, and distribute songs
              commercially — including on YouTube, Spotify, Apple Music, TikTok, and for use in
              advertising, film, television, and branded content.
            </li>
            <li>
              Songs generated during an active paid subscription retain their commercial rights
              even if you later cancel or downgrade your plan.
            </li>
            <li>
              Pay-as-you-go song credit purchases (without a subscription) also grant full
              commercial rights to songs generated using those credits.
            </li>
          </ul>

          <p><strong>AI disclosure requirement</strong></p>
          <p>
            When distributing or commercially releasing songs generated by Zeus Beats, you are
            required to disclose that the music was created with AI assistance wherever such
            disclosure is required by law, platform policy, or industry standard. We also strongly
            recommend proactive disclosure to audiences, labels, and collaborators even where not
            strictly required, in the interest of transparency.
          </p>

          <p><strong>No exclusivity guarantee</strong></p>
          <p>
            Zeus Beats does not warrant that your generated songs are unique or exclusive. Similar
            or identical outputs may be generated for other users from comparable prompts. For
            commercially significant works, we recommend registering with a performing rights
            organisation (PRO) such as PRS for Music to establish your authorship claim.
          </p>

          <p><strong>Underlying technology</strong></p>
          <p>
            Your ownership of generated outputs does not extend to the underlying AI models,
            software, algorithms, or technology used to create them. These remain the intellectual
            property of Zeus Beats Ltd and its third-party AI providers.
          </p>
        </section>

        <section className="content-section">
          <h2>11. Data Protection &amp; GDPR</h2>
          <p>
            Zeus Beats Ltd (company number 17230535,
            registered in England and Wales) is committed to protecting your personal data in
            accordance with the UK General Data Protection Regulation (UK GDPR), the Data
            Protection Act 2018, and applicable EU GDPR requirements. We act as the data
            controller for personal data processed through the Service. Zeus Beats Ltd
            is registered with the Information Commissioner's Office (ICO), registration
            number CSN5305083.
          </p>
          <p>
            <strong>Data we collect:</strong> We collect account information (name, email,
            encrypted password), usage data, generated content, payment information (via
            Stripe), and technical data such as IP addresses and browser type.
          </p>
          <p>
            <strong>Third-party processing:</strong> Stripe processes payment information.
            Railway provides cloud infrastructure. YouTube and Facebook integrations are
            processed through their respective APIs with your consent. Each of these processors
            operates under their own privacy policies and data processing agreements.
          </p>
          <p>
            <strong>Your rights:</strong> Under UK GDPR, you have the right to access, rectify,
            erase, and port your personal data, as well as the right to restrict or object to
            processing. To exercise your rights, contact us at{' '}
            <a href="mailto:hello@zeusbeats.com" className="auth-link">hello@zeusbeats.com</a>.
            You also have the right to lodge a complaint with the Information Commissioner's
            Office (ICO) at{' '}
            <a
              href="https://ico.org.uk"
              target="_blank"
              rel="noopener noreferrer"
              className="auth-link"
            >
              ico.org.uk
            </a>.
          </p>
          <p>
            For full details of how we handle your personal data, please read our{' '}
            <a href="/privacy" className="auth-link">Privacy Policy</a>.
          </p>
        </section>

        <section className="content-section">
          <h2>12. Limitation of Liability</h2>
          <p>
            To the maximum extent permitted by applicable law, Zeus Beats and its affiliates,
            directors, employees, and agents shall not be liable for any:
          </p>
          <ul>
            <li>Indirect, incidental, special, consequential, or punitive damages</li>
            <li>Loss of profits, revenue, data, or business opportunities</li>
            <li>Errors, inaccuracies, or omissions in AI-generated content</li>
            <li>Interruption or cessation of the Service</li>
            <li>Actions or outputs of third-party AI systems</li>
          </ul>
          <p>
            In no event shall our total aggregate liability exceed the greater of (a) the amount
            you paid to us in the 12 months preceding the claim or (b) £100. Nothing in these
            Terms limits liability for death, personal injury caused by negligence, fraud, or
            fraudulent misrepresentation, or any other liability that cannot be excluded under
            English law.
          </p>
        </section>

        <section className="content-section">
          <h2>13. Termination</h2>
          <p>
            We may terminate or suspend your access to the Service immediately, without notice,
            for any reason including breach of these Terms. Upon termination, your right to use
            the Service ceases immediately. You may request deletion of your account data in
            accordance with our Privacy Policy.
          </p>
          <p>
            You may terminate your account at any time by contacting us at{' '}
            <a href="mailto:hello@zeusbeats.com" className="auth-link">hello@zeusbeats.com</a>.
            Termination does not entitle you to a refund of any prepaid subscription fees outside
            the 7-day refund window.
          </p>
        </section>

        <section className="content-section">
          <h2>14. Governing Law</h2>
          <p>
            These Terms are governed by and construed in accordance with the laws of England and
            Wales. Any disputes arising under or in connection with these Terms shall be subject
            to the exclusive jurisdiction of the courts of England and Wales.
          </p>
          <p>
            If any provision of these Terms is found to be unenforceable, the remaining provisions
            will continue in full force and effect.
          </p>
        </section>

        <section className="content-section">
          <h2>15. Contact</h2>
          <p>
            If you have any questions about these Terms, please contact us at:
          </p>
          <address className="content-address">
            Zeus Beats Ltd<br />
            Company number: 17230535<br />
            Registered address: 79 Brookway Court, Wythenshawe, Manchester, M23 0GL<br />
            Registered in England and Wales<br />
            Email:{' '}
            <a href="mailto:hello@zeusbeats.com" className="auth-link">hello@zeusbeats.com</a><br />
            Website:{' '}
            <a href="https://zeusbeats.com" className="auth-link">zeusbeats.com</a>
          </address>
        </section>

        <section className="content-section">
          <h2>16. Contact &amp; Support</h2>
          <p>
            For general enquiries, support requests, or feedback, you can reach us via our{' '}
            <a href="/contact" className="auth-link">Contact page</a> or by emailing us directly
            at{' '}
            <a href="mailto:hello@zeusbeats.com" className="auth-link">hello@zeusbeats.com</a>.
            We aim to respond to all enquiries within 24 hours during business hours (Monday to
            Friday, 9am–5pm GMT).
          </p>
          <p>
            For account-specific issues, billing queries, or data subject requests, please include
            your registered email address and a brief description of the issue so we can assist
            you as quickly as possible.
          </p>
        </section>

        <section className="content-section">
          <h2>17. Governing Law</h2>
          <p>
            These Terms are governed by and construed in accordance with the laws of England and
            Wales. Any dispute or claim arising out of or in connection with these Terms or their
            subject matter or formation (including non-contractual disputes or claims) shall be
            subject to the exclusive jurisdiction of the courts of England and Wales.
          </p>
          <p>
            If you are a consumer resident in another jurisdiction, you may also benefit from any
            mandatory provisions of the law of your country of residence.
          </p>
          <p>
            If any provision of these Terms is found to be invalid or unenforceable by a court of
            competent jurisdiction, that provision shall be limited or eliminated to the minimum
            extent necessary, and the remaining provisions will continue in full force and effect.
          </p>
        </section>

        <section className="content-section">
          <h2>18. Changes to Terms</h2>
          <p>
            We reserve the right to update or modify these Terms at any time to reflect changes
            in the Service, applicable law, or our business practices. When we make material
            changes, we will notify you by email to your registered address or via a prominent
            notice within the Service, at least 14 days before the changes take effect.
          </p>
          <p>
            Your continued use of the Service after the effective date of any revised Terms
            constitutes your acceptance of those changes. If you do not agree to the updated
            Terms, you must stop using the Service before the changes take effect and may cancel
            your subscription in accordance with Section 7 (Cancellation Policy).
          </p>
          <p>
            We encourage you to review these Terms periodically. The "Last updated" date at the
            top of this page indicates when the Terms were most recently revised.
          </p>
        </section>
      </main>
    </div>
  );
}
