import { BeatsNavbar } from '../components/BeatsNavbar';

export default function TermsPage() {
  return (
    <div className="content-page-wrap">
      <BeatsNavbar />
      <div className="hero-orbs" aria-hidden>
        <div className="orb orb-1" style={{ opacity: 0.3 }} />
      </div>
      <main className="content-page page">
        <h1 className="content-title">Terms &amp; Conditions</h1>
        <p className="content-meta">Last updated: 3 April 2026</p>

        <section className="content-section">
          <h2>1. Acceptance of Terms</h2>
          <p>
            By accessing or using Zeus Beats ("the Service"), you agree to be bound by these
            Terms &amp; Conditions ("Terms"). If you do not agree to these Terms, you must not use
            the Service. These Terms constitute a legally binding agreement between you and Aero
            Space Parking Ltd (company number 17141941), trading as Zeus Beats ("we", "us",
            "our"), a company registered in England and Wales. We reserve the right to update these
            Terms at any time. Continued use of the Service after changes constitutes acceptance of
            the updated Terms.
          </p>
        </section>

        <section className="content-section">
          <h2>2. Service Description</h2>
          <p>
            Zeus Beats is an AI-powered SaaS platform designed to help musicians, content creators,
            and businesses with tasks including: AI music generation, cover art creation, avatar
            lip-sync videos, YouTube uploads, and automated social media posting.
          </p>
          <p>
            The Service is provided "as is" and we make no warranties that outputs will be
            error-free, complete, or suitable for any particular purpose. AI-generated content
            should always be reviewed before use in commercial or client-facing work. Zeus Beats
            does not provide legal, financial, tax, or professional advice, and nothing in the
            Service should be construed as such.
          </p>
        </section>

        <section className="content-section">
          <h2>3. AI-Powered Service &amp; Third-Party Disclaimer</h2>
          <p>
            Zeus Beats uses third-party AI systems to generate music, lyrics, cover art, and
            videos. By using the Service, you acknowledge and agree to the following:
          </p>
          <ul>
            <li>
              <strong>AI-generated outputs:</strong> All music, lyrics, images, and videos
              produced by Zeus Beats are generated by artificial intelligence. They may contain
              errors, inaccuracies, or unintended content. You are solely responsible for
              reviewing the suitability of any AI-generated output before use.
            </li>
            <li>
              <strong>Content processing:</strong> Your prompts and requests are transmitted to
              and processed by third-party AI systems in order to generate outputs. By using the
              Service, you consent to your inputs being processed by our AI providers.
            </li>
            <li>
              <strong>No sensitive data in prompts:</strong> You should not include sensitive
              personal data, financial information, passwords, or confidential third-party
              information in your prompts.
            </li>
            <li>
              <strong>No guarantee of accuracy:</strong> We make no warranty that AI outputs
              are accurate, current, or complete. Zeus Beats expressly disclaims liability
              for any reliance placed on AI-generated content.
            </li>
          </ul>
        </section>

        <section className="content-section">
          <h2>4. Account Registration</h2>
          <p>
            To access the full Service, you must create an account by providing accurate and
            complete information. You are responsible for:
          </p>
          <ul>
            <li>Maintaining the confidentiality of your password and account credentials</li>
            <li>All activity that occurs under your account</li>
            <li>Notifying us immediately of any unauthorised use of your account</li>
            <li>Ensuring all registration information is kept accurate and up to date</li>
          </ul>
          <p>
            You must be at least 18 years of age to create an account. By registering, you
            confirm that you meet this requirement and that you are not prohibited from using the
            Service under any applicable law.
          </p>
        </section>

        <section className="content-section">
          <h2>5. Payment Terms &amp; Subscriptions</h2>
          <p>
            Zeus Beats offers a free tier and paid subscription plans (Music Starter at £9/month,
            Music Pro at £19/month, and Music Agency at £39/month). All prices are shown in
            British Pounds (GBP) and are inclusive of VAT where applicable.
          </p>
          <p>
            Paid subscriptions are billed monthly in advance on your subscription anniversary
            date. By subscribing, you authorise us to charge your payment method on a recurring
            basis until you cancel. Payment is processed by Stripe; we do not store your full
            card details. Your payment information is subject to{' '}
            <a
              href="https://stripe.com/privacy"
              target="_blank"
              rel="noopener noreferrer"
              className="auth-link"
            >
              Stripe's Privacy Policy
            </a>.
          </p>
          <p>
            We reserve the right to change subscription prices with 30 days' written notice via
            email. Price changes will not affect your current billing period.
          </p>
        </section>

        <section className="content-section">
          <h2>6. Refund Policy</h2>
          <p>
            We offer a <strong>7-day refund window</strong> from the date of your initial
            subscription payment. If you are not satisfied with the Service, you may request a
            full refund within 7 days of your first payment by contacting us at{' '}
            <a href="mailto:dominic.rowle@yahoo.com" className="auth-link">dominic.rowle@yahoo.com</a>.
          </p>
          <p>
            <strong>After 7 days, no refunds will be issued</strong> for any subscription fees
            already paid, including in the event of cancellation, suspension, or termination of
            your account. This applies to both monthly subscription fees and any one-time charges.
          </p>
          <p>
            Refunds are not available for:
          </p>
          <ul>
            <li>Partial months of subscription after cancellation</li>
            <li>Accounts suspended or terminated for breach of these Terms</li>
            <li>Renewed subscription periods after the initial 7-day window has passed</li>
          </ul>
          <p>
            Nothing in this refund policy affects your statutory rights under the Consumer Rights
            Act 2015 or any other applicable UK consumer protection legislation.
          </p>
        </section>

        <section className="content-section">
          <h2>7. Cancellation Policy</h2>
          <p>
            You may cancel your subscription at any time through the Billing section of your
            account or by contacting us at{' '}
            <a href="mailto:dominic.rowle@yahoo.com" className="auth-link">dominic.rowle@yahoo.com</a>.
          </p>
          <p>
            Upon cancellation:
          </p>
          <ul>
            <li>
              Your subscription will remain active until the end of the current billing period
            </li>
            <li>
              You will not be charged for the next billing period
            </li>
            <li>
              Your account will revert to the free tier at the end of the paid period
            </li>
            <li>
              No partial-month refunds are issued for early cancellation (except within the
              7-day refund window described above)
            </li>
          </ul>
          <p>
            We reserve the right to cancel or suspend your account immediately for breach of
            these Terms, without notice and without refund.
          </p>
        </section>

        <section className="content-section">
          <h2>8. Acceptable Use</h2>
          <p>You agree not to use the Service to:</p>
          <ul>
            <li>Generate, distribute, or store illegal content of any kind</li>
            <li>Infringe upon the intellectual property rights of any third party</li>
            <li>Create content intended to deceive, harass, threaten, or harm any individual</li>
            <li>Attempt to reverse-engineer or extract the underlying AI models</li>
            <li>Resell or sublicense access to the Service without our written consent</li>
            <li>Use automated scripts or bots to access the Service beyond normal usage</li>
            <li>Upload or transmit content that violates any applicable law or regulation</li>
            <li>Circumvent usage limits, access controls, or subscription restrictions</li>
          </ul>
          <p>
            We reserve the right to suspend or terminate accounts that violate these acceptable
            use policies, without notice and without refund.
          </p>
        </section>

        <section className="content-section">
          <h2>9. Intellectual Property</h2>
          <p>
            <strong>Our IP:</strong> The Zeus Beats platform, its software, design, branding,
            and underlying technology are owned by us and protected by copyright, trademark, and
            other intellectual property laws. You may not copy, modify, distribute, or create
            derivative works from our platform without express written permission.
          </p>
          <p>
            <strong>Your content:</strong> You retain ownership of any content you submit to the
            Service (your prompts, uploaded files, and generated songs). By using the Service, you
            grant us a limited, non-exclusive, royalty-free licence to process your content
            solely for the purpose of delivering the Service.
          </p>
          <p>
            <strong>AI-generated outputs:</strong> Music, lyrics, images, and videos generated by
            Zeus Beats in response to your prompts are provided for your use. You are responsible
            for ensuring that AI-generated outputs do not infringe third-party intellectual
            property rights before any commercial use.
          </p>
        </section>

        <section className="content-section">
          <h2>10. Data Protection &amp; GDPR</h2>
          <p>
            Aero Space Parking Ltd (trading as Zeus Beats, company number 17141941,
            registered in England and Wales) is committed to protecting your personal data in
            accordance with the UK General Data Protection Regulation (UK GDPR), the Data
            Protection Act 2018, and applicable EU GDPR requirements. We act as the data
            controller for personal data processed through the Service. Aero Space Parking Ltd
            is registered with the Information Commissioner's Office (ICO), registration
            number C1903581.
          </p>
          <p>
            <strong>Data we collect:</strong> We collect account information (name, email,
            encrypted password), usage data, generated content, payment information (via
            Stripe), and technical data such as IP addresses and browser type.
          </p>
          <p>
            <strong>Third-party processing:</strong> Stripe processes payment information.
            Railway provides cloud infrastructure. YouTube and Facebook integrations are
            processed through their respective APIs with your consent. Each of these processors
            operates under their own privacy policies and data processing agreements.
          </p>
          <p>
            <strong>Your rights:</strong> Under UK GDPR, you have the right to access, rectify,
            erase, and port your personal data, as well as the right to restrict or object to
            processing. To exercise your rights, contact us at{' '}
            <a href="mailto:dominic.rowle@yahoo.com" className="auth-link">dominic.rowle@yahoo.com</a>.
            You also have the right to lodge a complaint with the Information Commissioner's
            Office (ICO) at{' '}
            <a
              href="https://ico.org.uk"
              target="_blank"
              rel="noopener noreferrer"
              className="auth-link"
            >
              ico.org.uk
            </a>.
          </p>
          <p>
            For full details of how we handle your personal data, please read our{' '}
            <a href="/privacy" className="auth-link">Privacy Policy</a>.
          </p>
        </section>

        <section className="content-section">
          <h2>11. Limitation of Liability</h2>
          <p>
            To the maximum extent permitted by applicable law, Zeus Beats and its affiliates,
            directors, employees, and agents shall not be liable for any:
          </p>
          <ul>
            <li>Indirect, incidental, special, consequential, or punitive damages</li>
            <li>Loss of profits, revenue, data, or business opportunities</li>
            <li>Errors, inaccuracies, or omissions in AI-generated content</li>
            <li>Interruption or cessation of the Service</li>
            <li>Actions or outputs of third-party AI systems</li>
          </ul>
          <p>
            In no event shall our total aggregate liability exceed the greater of (a) the amount
            you paid to us in the 12 months preceding the claim or (b) £100. Nothing in these
            Terms limits liability for death, personal injury caused by negligence, fraud, or
            fraudulent misrepresentation, or any other liability that cannot be excluded under
            English law.
          </p>
        </section>

        <section className="content-section">
          <h2>12. Termination</h2>
          <p>
            We may terminate or suspend your access to the Service immediately, without notice,
            for any reason including breach of these Terms. Upon termination, your right to use
            the Service ceases immediately. You may request deletion of your account data in
            accordance with our Privacy Policy.
          </p>
          <p>
            You may terminate your account at any time by contacting us at{' '}
            <a href="mailto:dominic.rowle@yahoo.com" className="auth-link">dominic.rowle@yahoo.com</a>.
            Termination does not entitle you to a refund of any prepaid subscription fees outside
            the 7-day refund window.
          </p>
        </section>

        <section className="content-section">
          <h2>13. Governing Law</h2>
          <p>
            These Terms are governed by and construed in accordance with the laws of England and
            Wales. Any disputes arising under or in connection with these Terms shall be subject
            to the exclusive jurisdiction of the courts of England and Wales.
          </p>
          <p>
            If any provision of these Terms is found to be unenforceable, the remaining provisions
            will continue in full force and effect.
          </p>
        </section>

        <section className="content-section">
          <h2>14. Contact</h2>
          <p>
            If you have any questions about these Terms, please contact us at:
          </p>
          <address className="content-address">
            Aero Space Parking Ltd<br />
            Trading as: Zeus Beats<br />
            Company number: 17141941<br />
            Registered in England and Wales<br />
            Email:{' '}
            <a href="mailto:dominic.rowle@yahoo.com" className="auth-link">dominic.rowle@yahoo.com</a><br />
            Website:{' '}
            <a href="https://zeusbeats.com" className="auth-link">zeusbeats.com</a>
          </address>
        </section>
      </main>
    </div>
  );
}
