import asyncio
import httpx
import json
import logging
import os
import pathlib
import sys
import traceback
from contextlib import asynccontextmanager
from datetime import datetime, timezone

# Log to stderr immediately — before basicConfig — so Railway captures startup
# crashes even if the import chain below fails.
print("zeus main.py: starting imports", file=sys.stderr, flush=True)

from fastapi import Depends, FastAPI, Header, HTTPException, Query, Request, WebSocket, WebSocketDisconnect
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import FileResponse, HTMLResponse, JSONResponse, Response
from pydantic import BaseModel, Field

print("zeus main.py: fastapi ok", file=sys.stderr, flush=True)

from zeus_agent import HistoryStore, get_anthropic_client, run_turn_stream

print("zeus main.py: zeus_agent ok", file=sys.stderr, flush=True)

from tunnel import get_tunnel_url, start_tunnel_background, stop_tunnel

import db
import auth
import billing
import scheduler as _scheduler_mod

import io
import re as _re

from fpdf import FPDF
from docx import Document as DocxDocument
from docx.oxml import OxmlElement


def slugify(text: str) -> str:
    text = text.lower()
    text = _re.sub(r'[^a-z0-9\s-]', '', text)
    text = _re.sub(r'[\s-]+', '-', text).strip('-')
    return text[:60]


def generate_pdf(text: str, title: str) -> bytes:
    pdf = FPDF()
    pdf.add_page()
    pdf.set_margins(20, 20, 20)

    # Title
    pdf.set_font("Helvetica", style="B", size=18)
    pdf.cell(0, 12, title, align="C", new_x="LMARGIN", new_y="NEXT")

    # Horizontal rule
    pdf.set_draw_color(180, 180, 180)
    pdf.set_line_width(0.5)
    pdf.line(20, pdf.get_y(), 190, pdf.get_y())
    pdf.ln(4)

    # Body
    pdf.set_font("Helvetica", size=11)
    pdf.set_text_color(30, 30, 30)
    for para in text.split("\n\n"):
        para = para.strip()
        if not para:
            continue
        pdf.multi_cell(0, 6, para)
        pdf.ln(4)

    # Footer
    pdf.set_y(-15)
    pdf.set_font("Helvetica", size=8)
    pdf.set_text_color(150, 150, 150)
    pdf.cell(0, 5, "Generated by Zeus \u00b7 zeusaidesign.com", align="C")

    return bytes(pdf.output())


def generate_docx(text: str, title: str) -> bytes:
    doc = DocxDocument()

    # Title as Heading 1
    doc.add_heading(title, level=1)

    # Body — double-newline = paragraph, single-newline = line break within paragraph
    for para_text in text.split("\n\n"):
        para_text = para_text.strip()
        if not para_text:
            continue
        lines = para_text.split("\n")
        para = doc.add_paragraph(lines[0])
        for line in lines[1:]:
            # Word line break must be in its own run before the text run
            br_run = para.add_run()
            br = OxmlElement("w:br")
            br_run._r.append(br)
            para.add_run(line)

    buf = io.BytesIO()
    doc.save(buf)
    return buf.getvalue()


def _send_task_email(
    user_email: str,
    description: str,
    live_url: str | None,
    result: str,
) -> None:
    """Send a task completion email via Gmail SMTP. Silently skips if not configured."""
    import smtplib
    from email.mime.multipart import MIMEMultipart
    from email.mime.text import MIMEText

    smtp_email = os.environ.get("SMTP_EMAIL", "").strip()
    smtp_password = os.environ.get("SMTP_PASSWORD", "").strip()
    if not smtp_email or not smtp_password:
        log.warning("_send_task_email: SMTP_EMAIL/SMTP_PASSWORD not set — skipping")
        return

    subject = f"Zeus: Your background task is complete — {description}"
    body = "\n".join([
        "Your background task has finished.",
        "",
        f"Task: {description}",
        f"Live URL: {live_url or 'See result below'}",
        "",
        "Result:",
        result[:2000],
        "",
        "— Zeus AI Design",
        "zeusaidesign.com",
    ])

    msg = MIMEMultipart()
    msg["From"] = smtp_email
    msg["To"] = user_email
    msg["Subject"] = subject
    msg.attach(MIMEText(body, "plain"))

    try:
        with smtplib.SMTP_SSL("smtp.gmail.com", 465, timeout=20) as server:
            server.login(smtp_email, smtp_password)
            server.sendmail(smtp_email, [user_email], msg.as_string())
        log.info("_send_task_email: sent to %s", user_email)
    except smtplib.SMTPAuthenticationError:
        log.warning("_send_task_email: Gmail auth failed — check SMTP_PASSWORD is an App Password")
    except smtplib.SMTPException as exc:
        log.warning("_send_task_email: SMTP error: %s", exc)


_RAILWAY = bool(os.environ.get("RAILWAY_ENVIRONMENT") or os.environ.get("RAILWAY_PROJECT_ID"))
_REQUIRE_AUTH = os.environ.get("REQUIRE_AUTH", "").strip() == "1"

print("zeus main.py: tunnel ok", file=sys.stderr, flush=True)

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
)
log = logging.getLogger("zeus")

# Log installed packages once so Railway deploy logs show the exact environment.
try:
    import importlib.metadata as _meta
    _pkgs = {d.metadata["Name"]: d.version for d in _meta.distributions()}
    for _name in ("fastapi", "starlette", "uvicorn", "anthropic", "httpx", "anyio"):
        log.info("pkg %s==%s", _name, _pkgs.get(_name, "NOT INSTALLED"))
except Exception:
    log.exception("could not enumerate installed packages")

history: HistoryStore | None = None
_background_tasks: set = set()

_parse_cache: dict[str, dict] = {}

_SCHEDULED_TASK_LIMITS = {"pro": 5, "agency": 20, "enterprise": None}


def _scheduled_task_plan_allowed(user: dict) -> bool:
    """Return True if user's plan includes scheduled tasks."""
    plan = user.get("subscription_plan")
    status = user.get("subscription_status", "free")
    is_admin = bool(user.get("is_admin", 0))
    return is_admin or (status == "active" and plan in _SCHEDULED_TASK_LIMITS)


def _scheduled_task_limit(user: dict) -> int | None:
    """Return max active scheduled tasks for user's plan, or None for unlimited."""
    if user.get("is_admin"):
        return None
    return _SCHEDULED_TASK_LIMITS.get(user.get("subscription_plan"))


@asynccontextmanager
async def lifespan(app: FastAPI):
    global history
    log.info("Startup: initialising HistoryStore")
    _sensitive = {"ANTHROPIC_API_KEY", "SECRET_KEY", "DATABASE_URL", "PASSWORD", "JWT_SECRET",
                  "STRIPE_SECRET_KEY", "STRIPE_WEBHOOK_SECRET"}
    for _k, _v in sorted(os.environ.items()):
        _display = f"***({len(_v)} chars)" if _k in _sensitive else _v
        log.info("  ENV %s=%s", _k, _display)
    try:
        history = HistoryStore()
        log.info("HistoryStore ready at %s", history.dir)
    except Exception:
        log.exception("FATAL: HistoryStore init failed")
        raise

    # Initialise user tables in the same DB file
    try:
        _db_path = db.get_db_path()
        db.init_user_tables(_db_path)
        log.info("User tables initialised at %s", _db_path)
        db.fail_stale_tasks(_db_path)
        log.info("Stale running tasks marked as failed")
        # Ensure owner account always has enterprise + admin access
        _owner_email = "dominic.rowle@yahoo.com"
        _owner = db.get_user_by_email(_db_path, _owner_email)
        if _owner:
            db.update_user(_db_path, _owner["id"],
                           subscription_plan="enterprise",
                           subscription_status="active",
                           is_admin=1)
            log.info("Owner account %s set to enterprise/admin", _owner_email)
        else:
            log.info("Owner account %s not yet registered — will be promoted on first login", _owner_email)
    except Exception:
        log.exception("FATAL: user table init failed")
        raise

    api_key_set = bool(os.environ.get("ANTHROPIC_API_KEY", "").strip())
    log.info("ANTHROPIC_API_KEY present: %s", api_key_set)
    if not api_key_set:
        raise RuntimeError("ANTHROPIC_API_KEY is not set — add it to Railway → Service → Variables")
    get_anthropic_client()  # validate key and warm up client at startup
    log.info("Anthropic client initialised")
    try:
        _scheduler_mod.init_scheduler(history)
        log.info("Scheduler initialised")
        if _RAILWAY:
            log.info("Running on Railway — skipping cloudflared tunnel (not installed)")
            yield
        else:
            port = int(os.environ.get("PORT", 8000))
            task = asyncio.create_task(start_tunnel_background(port))
            _background_tasks.add(task)
            task.add_done_callback(_background_tasks.discard)
            yield
            task.cancel()
            stop_tunnel()
    finally:
        _scheduler_mod.shutdown_scheduler()
        log.info("Scheduler shut down")


app = FastAPI(lifespan=lifespan)


@app.exception_handler(Exception)
async def unhandled_exception_handler(request: Request, exc: Exception):
    log.exception("Unhandled error on %s %s", request.method, request.url.path)
    return JSONResponse(
        status_code=500,
        content={"detail": "Internal server error"},
    )


app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)


# ── Pydantic request models ───────────────────────────────────────────────────

class RegisterRequest(BaseModel):
    email: str
    password: str
    name: str
    tc_accepted: bool


class LoginRequest(BaseModel):
    email: str
    password: str


class CheckoutRequest(BaseModel):
    plan: str


class SetEnterpriseRequest(BaseModel):
    email: str


class AdminUserPatchRequest(BaseModel):
    field: str   # "subscription_plan" or "subscription_status"
    value: str


class ExportRequest(BaseModel):
    text: str = Field(max_length=100_000)
    format: str   # "pdf" or "docx"
    title: str
    doc_type: str


# ── Auth routes ───────────────────────────────────────────────────────────────

@app.post("/auth/register")
async def register(body: RegisterRequest):
    if not body.tc_accepted:
        raise HTTPException(status_code=400, detail="You must accept the Terms & Conditions")

    if not body.email or "@" not in body.email:
        raise HTTPException(status_code=400, detail="Invalid email address")

    if len(body.password) < 8:
        raise HTTPException(status_code=400, detail="Password must be at least 8 characters")

    try:
        db_path = db.get_db_path()
    except Exception as exc:
        log.exception("register: failed to get DB path")
        raise HTTPException(status_code=500, detail=f"Database unavailable: {exc}")

    existing = db.get_user_by_email(db_path, body.email)
    if existing:
        raise HTTPException(status_code=409, detail="An account with that email already exists")

    try:
        password_hash = auth.hash_password(body.password)
    except Exception as exc:
        log.exception("register: password hashing failed")
        raise HTTPException(status_code=500, detail=f"Password hashing failed: {exc}")

    tc_accepted_at = datetime.now(timezone.utc).isoformat()

    try:
        user = db.create_user(
            db_path,
            email=body.email,
            password_hash=password_hash,
            name=body.name.strip(),
            tc_accepted_at=tc_accepted_at,
        )
    except Exception as exc:
        log.exception("register: create_user failed")
        raise HTTPException(status_code=500, detail=f"Could not create account: {exc}")

    # Create Stripe customer if Stripe is enabled
    if billing.stripe_enabled():
        customer_id = billing.create_stripe_customer(user)
        if customer_id:
            db.update_user(db_path, user["id"], stripe_customer_id=customer_id)
            user = db.get_user_by_id(db_path, user["id"])

    token = auth.create_token(user["id"], user["email"], is_admin=bool(user.get("is_admin", 0)))
    safe_user = {k: v for k, v in user.items() if k != "password_hash"}

    return {"token": token, "user": safe_user}


@app.post("/auth/login")
async def login(body: LoginRequest):
    try:
        db_path = db.get_db_path()
    except Exception as exc:
        log.exception("login: failed to get DB path")
        raise HTTPException(status_code=500, detail=f"Database unavailable: {exc}")

    user = db.get_user_by_email(db_path, body.email)

    try:
        password_ok = user and auth.verify_password(body.password, user["password_hash"])
    except Exception as exc:
        log.exception("login: password verification failed")
        raise HTTPException(status_code=500, detail=f"Authentication error: {exc}")

    if not password_ok:
        raise HTTPException(status_code=401, detail="Invalid email or password")

    token = auth.create_token(user["id"], user["email"], is_admin=bool(user.get("is_admin", 0)))
    safe_user = {k: v for k, v in user.items() if k != "password_hash"}

    return {"token": token, "user": safe_user}


@app.get("/auth/me")
async def me(current_user: dict = Depends(auth.get_current_user)):
    safe_user = {k: v for k, v in current_user.items() if k != "password_hash"}
    return safe_user


# ── Billing routes ────────────────────────────────────────────────────────────

@app.get("/billing/plans")
async def get_plans():
    return billing.PLANS


@app.post("/billing/checkout")
async def create_checkout(
    body: CheckoutRequest,
    current_user: dict = Depends(auth.get_current_user),
):
    if not billing.stripe_enabled():
        raise HTTPException(status_code=503, detail="Billing is not configured")

    origin = os.environ.get("FRONTEND_URL", "http://localhost:5173")
    success_url = f"{origin}/billing?success=true"
    cancel_url = f"{origin}/pricing"

    try:
        url = billing.create_checkout_session(
            current_user, body.plan, success_url, cancel_url
        )
    except ValueError as exc:
        raise HTTPException(status_code=400, detail=str(exc))
    except Exception as exc:
        log.exception("Stripe checkout error")
        raise HTTPException(status_code=500, detail="Failed to create checkout session")

    return {"url": url}


@app.get("/billing/portal")
async def billing_portal(current_user: dict = Depends(auth.get_current_user)):
    if not billing.stripe_enabled():
        raise HTTPException(status_code=503, detail="Billing is not configured")

    customer_id = current_user.get("stripe_customer_id")
    if not customer_id:
        raise HTTPException(status_code=400, detail="No billing account found. Please subscribe first.")

    origin = os.environ.get("FRONTEND_URL", "http://localhost:5173")
    return_url = f"{origin}/billing"

    try:
        url = billing.create_portal_session(customer_id, return_url)
    except Exception as exc:
        log.exception("Stripe portal error")
        raise HTTPException(status_code=500, detail="Failed to create portal session")

    return {"url": url}


@app.get("/billing/status")
async def billing_status(current_user: dict = Depends(auth.get_current_user)):
    return billing.get_subscription_status(current_user)


@app.post("/billing/webhook")
async def stripe_webhook(request: Request):
    payload = await request.body()
    sig = request.headers.get("stripe-signature", "")

    if not billing.stripe_enabled():
        raise HTTPException(status_code=503, detail="Billing not configured")

    try:
        billing.handle_webhook(payload, sig)
    except ValueError as exc:
        raise HTTPException(status_code=400, detail=str(exc))
    except Exception as exc:
        log.exception("Webhook handling error")
        raise HTTPException(status_code=500, detail="Webhook processing failed")

    return {"received": True}


@app.post("/webhook/stripe")
async def stripe_webhook_v2(request: Request):
    payload = await request.body()
    sig = request.headers.get("stripe-signature", "")

    if not billing.stripe_enabled():
        raise HTTPException(status_code=503, detail="Billing not configured")

    try:
        billing.handle_webhook(payload, sig)
    except ValueError as exc:
        raise HTTPException(status_code=400, detail=str(exc))
    except Exception as exc:
        log.exception("Webhook handling error")
        raise HTTPException(status_code=500, detail="Webhook processing failed")

    return {"received": True}


# ── WebSocket chat endpoint ───────────────────────────────────────────────────

@app.websocket("/chat")
async def chat_endpoint(websocket: WebSocket, token: str = Query(None)):
    await websocket.accept()

    if history is None:
        await websocket.send_json({"type": "error", "message": "Server still initialising"})
        await websocket.send_json({"type": "done"})
        await websocket.close()
        return

    # Auth check — required if REQUIRE_AUTH=1 env var is set, optional otherwise (dev compat)
    current_user: dict | None = None
    if _REQUIRE_AUTH or token:
        if not token:
            await websocket.send_json({"type": "error", "message": "Authentication required"})
            await websocket.send_json({"type": "done"})
            await websocket.close()
            return

        payload = auth.verify_token(token)
        if not payload:
            await websocket.send_json({"type": "error", "message": "Invalid or expired token"})
            await websocket.send_json({"type": "done"})
            await websocket.close()
            return

        db_path = db.get_db_path()
        current_user = db.get_user_by_id(db_path, payload.get("sub", ""))
        if not current_user:
            # Token is cryptographically valid — DB record missing (e.g. after redeploy).
            # Reconstruct a minimal user from the token payload so chat still works.
            current_user = {
                "id": payload.get("sub", ""),
                "email": payload.get("email", ""),
                "subscription_status": "free",
                "subscription_plan": None,
            }

    # Usage / subscription check
    if current_user:
        db_path = db.get_db_path()
        status_info = billing.get_subscription_status(current_user)
        limit = status_info.get("messages_limit")
        if limit is not None and status_info["messages_used"] >= limit:
            await websocket.send_json({
                "type": "error",
                "message": (
                    f"You've reached the free limit of {billing.FREE_LIMIT} messages. "
                    "Upgrade to Pro for unlimited messages at /pricing"
                ),
            })
            await websocket.send_json({"type": "done"})
            await websocket.close()
            return

    try:
        data = await websocket.receive_json()
        prompt = data.get("prompt", "").strip()
        session_id = data.get("session_id")
        image = data.get("image")  # optional: {data: base64str, media_type: str}

        if not prompt and not image:
            await websocket.send_json({"type": "error", "message": "prompt is required"})
            await websocket.send_json({"type": "done"})
            await websocket.close()
            return

        # Validate image payload if present
        if image and (not isinstance(image, dict) or not image.get("data") or not image.get("media_type")):
            image = None

        async def send(msg: dict):
            await websocket.send_json(msg)

        await run_turn_stream(prompt, session_id, send, history, user_id=current_user["id"] if current_user else None, image=image)

        # Increment usage after successful response
        if current_user:
            month = datetime.now(timezone.utc).strftime("%Y-%m")
            db.increment_usage(db.get_db_path(), current_user["id"], month)

        await websocket.close()

    except WebSocketDisconnect:
        pass
    except Exception as exc:
        try:
            await websocket.send_json({"type": "error", "message": str(exc)})
            await websocket.send_json({"type": "done"})
            await websocket.close()
        except Exception:
            pass


# ── Admin endpoints ───────────────────────────────────────────────────────────

@app.post("/admin/set-enterprise")
async def admin_set_enterprise(
    body: SetEnterpriseRequest,
    x_admin_secret: str = Header(None, alias="X-Admin-Secret"),
):
    admin_secret = os.environ.get("ADMIN_SECRET", "").strip()
    if not admin_secret or x_admin_secret != admin_secret:
        raise HTTPException(status_code=403, detail="Invalid or missing admin secret")

    db_path = db.get_db_path()
    user = db.get_user_by_email(db_path, body.email)
    if not user:
        raise HTTPException(status_code=404, detail=f"No user found with email {body.email!r}")

    db.update_user(
        db_path, user["id"],
        subscription_plan="enterprise",
        subscription_status="active",
    )
    log.info("admin_set_enterprise: set %s to enterprise", body.email)
    return {"ok": True, "email": body.email, "plan": "enterprise", "status": "active"}


@app.get("/admin/users")
async def admin_list_users(current_user: dict = Depends(auth.get_current_user)):
    if not current_user.get("is_admin"):
        raise HTTPException(status_code=403, detail="Admin access required")
    db_path = db.get_db_path()
    log.info("admin_list_users: querying db at %s", db_path)
    users = db.get_all_users(db_path)
    log.info("admin_list_users: get_all_users returned %d row(s): %s",
             len(users), [u.get("email") for u in users])
    month = datetime.now(timezone.utc).strftime("%Y-%m")
    for u in users:
        u.pop("password_hash", None)
        u["messages_this_month"] = db.get_monthly_usage(db_path, u["id"], month)
    return users


_ALLOWED_ADMIN_FIELDS = {
    "subscription_plan": {"free", "pro", "agency", "enterprise"},
    "subscription_status": {"free", "active", "cancelled"},
}


@app.patch("/admin/users/{user_id}")
async def admin_patch_user(
    user_id: str,
    body: AdminUserPatchRequest,
    current_user: dict = Depends(auth.get_current_user),
):
    if not current_user.get("is_admin"):
        raise HTTPException(status_code=403, detail="Admin access required")
    allowed_values = _ALLOWED_ADMIN_FIELDS.get(body.field)
    if allowed_values is None:
        raise HTTPException(status_code=400, detail=f"Field '{body.field}' is not editable")
    if body.value not in allowed_values:
        raise HTTPException(
            status_code=400,
            detail=f"Value '{body.value}' not allowed for '{body.field}'. Allowed: {sorted(allowed_values)}",
        )
    db_path = db.get_db_path()
    target = db.get_user_by_id(db_path, user_id)
    if not target:
        raise HTTPException(status_code=404, detail="User not found")
    db.update_user(db_path, user_id, **{body.field: body.value})
    log.info("admin_patch_user: set %s.%s = %s (by admin %s)", user_id, body.field, body.value, current_user["id"])
    return {"ok": True}


@app.get("/admin/credits")
async def admin_credits(current_user: dict = Depends(auth.get_current_user)):
    if not current_user.get("is_admin"):
        raise HTTPException(status_code=403, detail="Admin access required")
    api_key = os.environ.get("ANTHROPIC_API_KEY", "").strip()
    if not api_key:
        return {"balance": None, "message": "Balance unavailable"}
    try:
        async with httpx.AsyncClient() as client:
            resp = await client.get(
                "https://api.anthropic.com/v1/organizations/credits/balance",
                headers={
                    "x-api-key": api_key,
                    "anthropic-version": "2023-06-01",
                },
                timeout=10,
            )
        if resp.status_code != 200:
            return {"balance": None, "message": "Balance unavailable"}
        data = resp.json()
        # Response shape: {"balance": {"available": [{"amount": 1234, "currency": "USD"}]}}
        available = data.get("balance", {}).get("available", [])
        if available:
            amount_cents = available[0].get("amount", 0)
            currency = available[0].get("currency", "USD")
            return {"balance": round(amount_cents / 100, 2), "currency": currency}
        return {"balance": None, "message": "Balance unavailable"}
    except Exception:
        log.exception("admin_credits: failed to fetch Anthropic balance")
        return {"balance": None, "message": "Balance unavailable"}


# ── Scheduled Tasks ─────────────────────────────────────────────────────────

class ScheduledTaskParseRequest(BaseModel):
    natural_language: str = Field(min_length=1, max_length=500)


@app.post("/scheduled-tasks/parse")
async def parse_scheduled_task(
    body: ScheduledTaskParseRequest,
    current_user: dict = Depends(auth.get_current_user),
):
    """Parse a natural language schedule into a cron expression. No plan gate."""
    key = body.natural_language.lower().strip()
    if key in _parse_cache:
        return _parse_cache[key]

    client = get_anthropic_client()
    try:
        msg = client.messages.create(
            model="claude-haiku-4-5-20251001",
            max_tokens=128,
            system=(
                "You extract cron expressions from natural language schedule descriptions. "
                'Respond with ONLY a JSON object: {"cron_expression": "...", "schedule_label": "..."}\n'
                "- cron_expression: standard 5-field cron (minute hour day month weekday)\n"
                '- schedule_label: concise human-readable label, e.g. "Every Monday at 9am"\n'
                "If you cannot parse the input into a valid cron expression, respond with:\n"
                '{"error": "Could not parse schedule — try something like \'every Monday at 9am\'"}\n'
                "Do not include any other text."
            ),
            messages=[{"role": "user", "content": body.natural_language}],
        )
    except Exception:
        log.exception("parse_scheduled_task: Anthropic call failed")
        raise HTTPException(status_code=503, detail="Schedule parsing timed out — try again")

    try:
        result = json.loads(msg.content[0].text)
    except Exception:
        raise HTTPException(status_code=400, detail="Could not parse schedule — try again")

    if "error" in result:
        raise HTTPException(status_code=400, detail=result["error"])

    if len(_parse_cache) < 1024:
        _parse_cache[key] = result
    return result


@app.get("/scheduled-tasks")
async def list_scheduled_tasks(
    db_path: pathlib.Path = Depends(db.get_db_path_dep),
    current_user: dict = Depends(auth.get_current_user),
):
    if not _scheduled_task_plan_allowed(current_user):
        raise HTTPException(status_code=403, detail="Scheduled tasks require a Pro plan or above.")
    return db.get_scheduled_tasks_for_user(db_path, current_user["id"])


class ScheduledTaskCreateRequest(BaseModel):
    task_description: str = Field(min_length=1, max_length=2000)
    cron_expression: str = Field(min_length=1, max_length=100)
    schedule_label: str = Field(min_length=1, max_length=200)
    timezone: str = "UTC"


@app.post("/scheduled-tasks")
async def create_scheduled_task_endpoint(
    body: ScheduledTaskCreateRequest,
    db_path: pathlib.Path = Depends(db.get_db_path_dep),
    current_user: dict = Depends(auth.get_current_user),
):
    if not _scheduled_task_plan_allowed(current_user):
        raise HTTPException(status_code=403, detail="Scheduled tasks require a Pro plan or above.")

    limit = _scheduled_task_limit(current_user)
    if limit is not None:
        active_count = db.count_active_scheduled_tasks(db_path, current_user["id"])
        if active_count >= limit:
            plan = current_user.get("subscription_plan", "")
            raise HTTPException(
                status_code=403,
                detail=f"You've reached the limit of {limit} scheduled tasks on the {plan} plan. Upgrade to add more.",
            )

    # Validate cron expression — must be exactly 5 fields (APScheduler rejects 6-field)
    try:
        from croniter import croniter
        parts = body.cron_expression.strip().split()
        if len(parts) != 5 or not croniter.is_valid(body.cron_expression):
            raise ValueError("invalid")
    except ValueError:
        raise HTTPException(status_code=400, detail="Invalid cron expression")

    next_run = _scheduler_mod.compute_next_run(body.cron_expression)
    task = db.create_scheduled_task(
        db_path,
        user_id=current_user["id"],
        task_description=body.task_description,
        cron_expression=body.cron_expression,
        schedule_label=body.schedule_label,
        next_run=next_run,
        tz=body.timezone,
    )
    _scheduler_mod.add_job(task)
    return task


@app.delete("/scheduled-tasks/{task_id}")
async def delete_scheduled_task_endpoint(
    task_id: str,
    db_path: pathlib.Path = Depends(db.get_db_path_dep),
    current_user: dict = Depends(auth.get_current_user),
):
    if not _scheduled_task_plan_allowed(current_user):
        raise HTTPException(status_code=403, detail="Scheduled tasks require a Pro plan or above.")
    deleted = db.delete_scheduled_task(db_path, task_id, current_user["id"])
    if not deleted:
        raise HTTPException(status_code=404, detail="Task not found")
    _scheduler_mod.remove_job(task_id)
    return {"ok": True}


@app.patch("/scheduled-tasks/{task_id}/toggle")
async def toggle_scheduled_task(
    task_id: str,
    db_path: pathlib.Path = Depends(db.get_db_path_dep),
    current_user: dict = Depends(auth.get_current_user),
):
    if not _scheduled_task_plan_allowed(current_user):
        raise HTTPException(status_code=403, detail="Scheduled tasks require a Pro plan or above.")

    task = db.get_scheduled_task(db_path, task_id)
    if not task or task["user_id"] != current_user["id"]:
        raise HTTPException(status_code=404, detail="Task not found")

    new_active = 0 if task["is_active"] else 1

    if new_active == 1:
        # Re-activation limit check — prevents circumventing plan limits by deactivating+reactivating
        limit = _scheduled_task_limit(current_user)
        if limit is not None:
            active_count = db.count_active_scheduled_tasks(db_path, current_user["id"])
            if active_count >= limit:
                plan = current_user.get("subscription_plan", "")
                raise HTTPException(
                    status_code=403,
                    detail=f"You've reached the limit of {limit} scheduled tasks on the {plan} plan.",
                )

    if new_active == 1:
        next_run = _scheduler_mod.compute_next_run(task["cron_expression"])
        db.update_scheduled_task(db_path, task_id, is_active=1, next_run=next_run)
        _scheduler_mod.set_job_enabled(task_id, True)
    else:
        db.update_scheduled_task(db_path, task_id, is_active=0)
        _scheduler_mod.set_job_enabled(task_id, False)

    return db.get_scheduled_task(db_path, task_id)


# ── Tasks endpoints ───────────────────────────────────────────────────────────

@app.get("/tasks")
async def get_tasks(current_user: dict = Depends(auth.get_current_user)):
    is_admin = bool(current_user.get("is_admin", 0))
    plan = current_user.get("subscription_plan")
    status = current_user.get("subscription_status", "free")
    if not (is_admin or (status == "active" and plan == "enterprise")):
        raise HTTPException(status_code=403, detail="Enterprise plan required")
    db_path = db.get_db_path()
    # Ensure tasks table exists (handles DBs initialised before this feature was added)
    db.init_user_tables(db_path)
    try:
        return db.get_tasks_for_user(db_path, current_user["id"])
    except Exception:
        log.exception("get_tasks: DB error for user %s", current_user["id"])
        return []


@app.delete("/tasks/{task_id}")
async def delete_task(task_id: str, current_user: dict = Depends(auth.get_current_user)):
    is_admin = bool(current_user.get("is_admin", 0))
    plan = current_user.get("subscription_plan")
    status = current_user.get("subscription_status", "free")
    if not (is_admin or (status == "active" and plan == "enterprise")):
        raise HTTPException(status_code=403, detail="Enterprise plan required")
    db_path = db.get_db_path()
    deleted = db.delete_task(db_path, task_id, current_user["id"])
    if not deleted:
        raise HTTPException(status_code=404, detail="Task not found")
    return {"ok": True}


# ── Existing REST endpoints ───────────────────────────────────────────────────

@app.get("/sessions")
async def get_sessions(current_user: dict = Depends(auth.get_current_user)):
    if history is None:
        return []
    return history.list_sessions_for_user(current_user["id"])


@app.get("/history/{session_id}")
async def get_history(session_id: str, current_user: dict = Depends(auth.get_current_user)):
    if history is None:
        raise HTTPException(status_code=503, detail="Server still initialising")
    transcript = history.get_transcript_if_owner(session_id, current_user["id"])
    if transcript is None:
        raise HTTPException(status_code=404, detail="Session not found")
    return transcript


@app.get("/tunnel-url")
async def tunnel_url_endpoint():
    return {"url": get_tunnel_url()}


@app.post("/export")
async def export_document(body: ExportRequest):
    if body.format == "pdf":
        file_bytes = generate_pdf(body.text, body.title)
        media_type = "application/pdf"
        filename = f"{slugify(body.title)}.pdf"
    elif body.format == "docx":
        file_bytes = generate_docx(body.text, body.title)
        media_type = "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
        filename = f"{slugify(body.title)}.docx"
    else:
        raise HTTPException(status_code=400, detail="format must be pdf or docx")
    return Response(
        content=file_bytes,
        media_type=media_type,
        headers={"Content-Disposition": f'attachment; filename="{filename}"'},
    )


@app.get("/download/{filename}")
async def download_file(filename: str):
    import tempfile
    _railway = bool(os.environ.get("RAILWAY_ENVIRONMENT") or os.environ.get("RAILWAY_PROJECT_ID"))
    downloads_dir = pathlib.Path("/data/downloads" if _railway else tempfile.gettempdir()) / "zeus_downloads"
    file_path = downloads_dir / filename
    # Prevent path traversal
    if not file_path.resolve().is_relative_to(downloads_dir.resolve()):
        raise HTTPException(status_code=400, detail="Invalid filename")
    if not file_path.exists():
        raise HTTPException(status_code=404, detail="File not found or expired")
    display_name = filename.split("_", 1)[-1] if "_" in filename else filename
    return Response(
        content=file_path.read_bytes(),
        media_type="application/zip",
        headers={
            "Content-Disposition": f'attachment; filename="{display_name}"',
            "Content-Length": str(file_path.stat().st_size),
        },
    )


@app.get("/sitemap.xml", include_in_schema=False)
async def sitemap():
    path = pathlib.Path(__file__).parent / "sitemap.xml"
    return Response(content=path.read_text(encoding="utf-8"), media_type="application/xml")


@app.get("/health")
async def health():
    log.info("GET /health — ok")
    return {"status": "ok"}


@app.get("/ad-poster", include_in_schema=False)
async def ad_poster():
    html = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Zeus AI Design</title>
<style>
  * { margin: 0; padding: 0; box-sizing: border-box; }

  body {
    width: 1200px;
    height: 630px;
    overflow: hidden;
    background: #000;
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
    display: flex;
    align-items: center;
    justify-content: center;
  }

  .card {
    width: 1200px;
    height: 630px;
    background: #000;
    position: relative;
    display: flex;
    flex-direction: column;
    align-items: flex-start;
    justify-content: center;
    padding: 80px 100px;
    overflow: hidden;
  }

  /* Grid overlay */
  .card::before {
    content: '';
    position: absolute;
    inset: 0;
    background-image:
      linear-gradient(rgba(0, 255, 65, 0.04) 1px, transparent 1px),
      linear-gradient(90deg, rgba(0, 255, 65, 0.04) 1px, transparent 1px);
    background-size: 60px 60px;
    pointer-events: none;
  }

  /* Glow bloom */
  .card::after {
    content: '';
    position: absolute;
    top: -200px;
    right: -200px;
    width: 700px;
    height: 700px;
    background: radial-gradient(circle, rgba(0, 255, 65, 0.12) 0%, transparent 70%);
    pointer-events: none;
  }

  .bolt {
    font-size: 72px;
    line-height: 1;
    margin-bottom: 24px;
    filter: drop-shadow(0 0 24px #00ff41);
  }

  .headline {
    font-size: 80px;
    font-weight: 800;
    color: #00ff41;
    letter-spacing: -2px;
    line-height: 1;
    text-shadow: 0 0 40px rgba(0, 255, 65, 0.5);
    margin-bottom: 8px;
  }

  .sub {
    font-size: 80px;
    font-weight: 800;
    color: #fff;
    letter-spacing: -2px;
    line-height: 1;
    margin-bottom: 32px;
  }

  .tagline {
    font-size: 26px;
    font-weight: 400;
    color: rgba(255, 255, 255, 0.55);
    letter-spacing: 0.5px;
    margin-bottom: 48px;
  }

  .url {
    font-size: 22px;
    font-weight: 600;
    color: #00ff41;
    letter-spacing: 1px;
    border: 1.5px solid rgba(0, 255, 65, 0.4);
    padding: 10px 24px;
    border-radius: 4px;
    text-transform: lowercase;
  }

  /* Corner accent lines */
  .corner {
    position: absolute;
    width: 40px;
    height: 40px;
    border-color: rgba(0, 255, 65, 0.3);
    border-style: solid;
  }
  .corner-tl { top: 32px; left: 32px; border-width: 2px 0 0 2px; }
  .corner-tr { top: 32px; right: 32px; border-width: 2px 2px 0 0; }
  .corner-bl { bottom: 32px; left: 32px; border-width: 0 0 2px 2px; }
  .corner-br { bottom: 32px; right: 32px; border-width: 0 2px 2px 0; }
</style>
</head>
<body>
  <div class="card">
    <div class="corner corner-tl"></div>
    <div class="corner corner-tr"></div>
    <div class="corner corner-bl"></div>
    <div class="corner corner-br"></div>

    <div class="bolt">⚡</div>
    <div class="headline">Zeus AI</div>
    <div class="sub">Design.</div>
    <div class="tagline">Websites · Writing · Research · Business — powered by AI</div>
    <div class="url">zeusaidesign.com</div>
  </div>
</body>
</html>"""
    return HTMLResponse(content=html)


# Serve built React app from web/dist/
# Mount /assets for Vite bundles, then a catch-all that returns index.html for
# any unmatched path so client-side routes (e.g. /tasks, /billing) survive refresh.
_dist = pathlib.Path(__file__).parent.parent / "web" / "dist"
if _dist.exists():
    from fastapi.staticfiles import StaticFiles
    from fastapi.responses import FileResponse

    _assets_dir = _dist / "assets"
    if _assets_dir.exists():
        app.mount("/assets", StaticFiles(directory=str(_assets_dir)), name="assets")

    @app.get("/{full_path:path}", include_in_schema=False)
    async def serve_spa(full_path: str):
        # Serve real files that live in dist root (favicon.ico, robots.txt, etc.)
        candidate = _dist / full_path
        if candidate.exists() and candidate.is_file():
            return FileResponse(str(candidate))
        # Fall back to index.html for all client-side routes
        return FileResponse(str(_dist / "index.html"))


if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000, reload=False)
