import asyncio
import logging
import os
import pathlib
import sys
import traceback
from contextlib import asynccontextmanager
from datetime import datetime, timezone

# Log to stderr immediately — before basicConfig — so Railway captures startup
# crashes even if the import chain below fails.
print("zeus main.py: starting imports", file=sys.stderr, flush=True)

from fastapi import Depends, FastAPI, Header, HTTPException, Query, Request, WebSocket, WebSocketDisconnect
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import FileResponse, JSONResponse, Response
from pydantic import BaseModel, Field

print("zeus main.py: fastapi ok", file=sys.stderr, flush=True)

from zeus_agent import HistoryStore, get_anthropic_client, run_turn_stream

print("zeus main.py: zeus_agent ok", file=sys.stderr, flush=True)

from tunnel import get_tunnel_url, start_tunnel_background, stop_tunnel

import db
import auth
import billing

import io
import re as _re

from fpdf import FPDF
from docx import Document as DocxDocument
from docx.oxml import OxmlElement


def slugify(text: str) -> str:
    text = text.lower()
    text = _re.sub(r'[^a-z0-9\s-]', '', text)
    text = _re.sub(r'[\s-]+', '-', text).strip('-')
    return text[:60]


def generate_pdf(text: str, title: str) -> bytes:
    pdf = FPDF()
    pdf.add_page()
    pdf.set_margins(20, 20, 20)

    # Title
    pdf.set_font("Helvetica", style="B", size=18)
    pdf.cell(0, 12, title, align="C", new_x="LMARGIN", new_y="NEXT")

    # Horizontal rule
    pdf.set_draw_color(180, 180, 180)
    pdf.set_line_width(0.5)
    pdf.line(20, pdf.get_y(), 190, pdf.get_y())
    pdf.ln(4)

    # Body
    pdf.set_font("Helvetica", size=11)
    pdf.set_text_color(30, 30, 30)
    for para in text.split("\n\n"):
        para = para.strip()
        if not para:
            continue
        pdf.multi_cell(0, 6, para)
        pdf.ln(4)

    # Footer
    pdf.set_y(-15)
    pdf.set_font("Helvetica", size=8)
    pdf.set_text_color(150, 150, 150)
    pdf.cell(0, 5, "Generated by Zeus \u00b7 zeusaidesign.com", align="C")

    return bytes(pdf.output())


def generate_docx(text: str, title: str) -> bytes:
    doc = DocxDocument()

    # Title as Heading 1
    doc.add_heading(title, level=1)

    # Body — double-newline = paragraph, single-newline = line break within paragraph
    for para_text in text.split("\n\n"):
        para_text = para_text.strip()
        if not para_text:
            continue
        lines = para_text.split("\n")
        para = doc.add_paragraph(lines[0])
        for line in lines[1:]:
            # Word line break must be in its own run before the text run
            br_run = para.add_run()
            br = OxmlElement("w:br")
            br_run._r.append(br)
            para.add_run(line)

    buf = io.BytesIO()
    doc.save(buf)
    return buf.getvalue()


def _send_task_email(
    user_email: str,
    description: str,
    live_url: str | None,
    result: str,
) -> None:
    """Send a task completion email via Gmail SMTP. Silently skips if not configured."""
    import smtplib
    from email.mime.multipart import MIMEMultipart
    from email.mime.text import MIMEText

    smtp_email = os.environ.get("SMTP_EMAIL", "").strip()
    smtp_password = os.environ.get("SMTP_PASSWORD", "").strip()
    if not smtp_email or not smtp_password:
        log.warning("_send_task_email: SMTP_EMAIL/SMTP_PASSWORD not set — skipping")
        return

    subject = f"Zeus: Your background task is complete — {description}"
    body = "\n".join([
        "Your background task has finished.",
        "",
        f"Task: {description}",
        f"Live URL: {live_url or 'See result below'}",
        "",
        "Result:",
        result[:2000],
        "",
        "— Zeus AI Design",
        "zeusaidesign.com",
    ])

    msg = MIMEMultipart()
    msg["From"] = smtp_email
    msg["To"] = user_email
    msg["Subject"] = subject
    msg.attach(MIMEText(body, "plain"))

    try:
        with smtplib.SMTP_SSL("smtp.gmail.com", 465, timeout=20) as server:
            server.login(smtp_email, smtp_password)
            server.sendmail(smtp_email, [user_email], msg.as_string())
        log.info("_send_task_email: sent to %s", user_email)
    except smtplib.SMTPAuthenticationError:
        log.warning("_send_task_email: Gmail auth failed — check SMTP_PASSWORD is an App Password")
    except smtplib.SMTPException as exc:
        log.warning("_send_task_email: SMTP error: %s", exc)


_RAILWAY = bool(os.environ.get("RAILWAY_ENVIRONMENT") or os.environ.get("RAILWAY_PROJECT_ID"))
_REQUIRE_AUTH = os.environ.get("REQUIRE_AUTH", "").strip() == "1"

print("zeus main.py: tunnel ok", file=sys.stderr, flush=True)

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
)
log = logging.getLogger("zeus")

# Log installed packages once so Railway deploy logs show the exact environment.
try:
    import importlib.metadata as _meta
    _pkgs = {d.metadata["Name"]: d.version for d in _meta.distributions()}
    for _name in ("fastapi", "starlette", "uvicorn", "anthropic", "httpx", "anyio"):
        log.info("pkg %s==%s", _name, _pkgs.get(_name, "NOT INSTALLED"))
except Exception:
    log.exception("could not enumerate installed packages")

history: HistoryStore | None = None
_background_tasks: set = set()


@asynccontextmanager
async def lifespan(app: FastAPI):
    global history
    log.info("Startup: initialising HistoryStore")
    _sensitive = {"ANTHROPIC_API_KEY", "SECRET_KEY", "DATABASE_URL", "PASSWORD", "JWT_SECRET",
                  "STRIPE_SECRET_KEY", "STRIPE_WEBHOOK_SECRET"}
    for _k, _v in sorted(os.environ.items()):
        _display = f"***({len(_v)} chars)" if _k in _sensitive else _v
        log.info("  ENV %s=%s", _k, _display)
    try:
        history = HistoryStore()
        log.info("HistoryStore ready at %s", history.dir)
    except Exception:
        log.exception("FATAL: HistoryStore init failed")
        raise

    # Initialise user tables in the same DB file
    try:
        _db_path = db.get_db_path()
        db.init_user_tables(_db_path)
        log.info("User tables initialised at %s", _db_path)
        db.fail_stale_tasks(_db_path)
        log.info("Stale running tasks marked as failed")
        # Ensure owner account always has enterprise + admin access
        _owner_email = "dominic.rowle@yahoo.com"
        _owner = db.get_user_by_email(_db_path, _owner_email)
        if _owner:
            db.update_user(_db_path, _owner["id"],
                           subscription_plan="enterprise",
                           subscription_status="active",
                           is_admin=1)
            log.info("Owner account %s set to enterprise/admin", _owner_email)
        else:
            log.info("Owner account %s not yet registered — will be promoted on first login", _owner_email)
    except Exception:
        log.exception("FATAL: user table init failed")
        raise

    api_key_set = bool(os.environ.get("ANTHROPIC_API_KEY", "").strip())
    log.info("ANTHROPIC_API_KEY present: %s", api_key_set)
    if not api_key_set:
        raise RuntimeError("ANTHROPIC_API_KEY is not set — add it to Railway → Service → Variables")
    get_anthropic_client()  # validate key and warm up client at startup
    log.info("Anthropic client initialised")
    if _RAILWAY:
        log.info("Running on Railway — skipping cloudflared tunnel (not installed)")
        yield
    else:
        port = int(os.environ.get("PORT", 8000))
        task = asyncio.create_task(start_tunnel_background(port))
        _background_tasks.add(task)
        task.add_done_callback(_background_tasks.discard)
        yield
        task.cancel()
        stop_tunnel()


app = FastAPI(lifespan=lifespan)


@app.exception_handler(Exception)
async def unhandled_exception_handler(request: Request, exc: Exception):
    log.exception("Unhandled error on %s %s", request.method, request.url.path)
    return JSONResponse(
        status_code=500,
        content={"detail": "Internal server error"},
    )


app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)


# ── Pydantic request models ───────────────────────────────────────────────────

class RegisterRequest(BaseModel):
    email: str
    password: str
    name: str
    tc_accepted: bool


class LoginRequest(BaseModel):
    email: str
    password: str


class CheckoutRequest(BaseModel):
    plan: str


class SetEnterpriseRequest(BaseModel):
    email: str


class ExportRequest(BaseModel):
    text: str = Field(max_length=100_000)
    format: str   # "pdf" or "docx"
    title: str
    doc_type: str


# ── Auth routes ───────────────────────────────────────────────────────────────

@app.post("/auth/register")
async def register(body: RegisterRequest):
    if not body.tc_accepted:
        raise HTTPException(status_code=400, detail="You must accept the Terms & Conditions")

    if not body.email or "@" not in body.email:
        raise HTTPException(status_code=400, detail="Invalid email address")

    if len(body.password) < 8:
        raise HTTPException(status_code=400, detail="Password must be at least 8 characters")

    try:
        db_path = db.get_db_path()
    except Exception as exc:
        log.exception("register: failed to get DB path")
        raise HTTPException(status_code=500, detail=f"Database unavailable: {exc}")

    existing = db.get_user_by_email(db_path, body.email)
    if existing:
        raise HTTPException(status_code=409, detail="An account with that email already exists")

    try:
        password_hash = auth.hash_password(body.password)
    except Exception as exc:
        log.exception("register: password hashing failed")
        raise HTTPException(status_code=500, detail=f"Password hashing failed: {exc}")

    tc_accepted_at = datetime.now(timezone.utc).isoformat()

    try:
        user = db.create_user(
            db_path,
            email=body.email,
            password_hash=password_hash,
            name=body.name.strip(),
            tc_accepted_at=tc_accepted_at,
        )
    except Exception as exc:
        log.exception("register: create_user failed")
        raise HTTPException(status_code=500, detail=f"Could not create account: {exc}")

    # Create Stripe customer if Stripe is enabled
    if billing.stripe_enabled():
        customer_id = billing.create_stripe_customer(user)
        if customer_id:
            db.update_user(db_path, user["id"], stripe_customer_id=customer_id)
            user = db.get_user_by_id(db_path, user["id"])

    token = auth.create_token(user["id"], user["email"])
    safe_user = {k: v for k, v in user.items() if k != "password_hash"}

    return {"token": token, "user": safe_user}


@app.post("/auth/login")
async def login(body: LoginRequest):
    try:
        db_path = db.get_db_path()
    except Exception as exc:
        log.exception("login: failed to get DB path")
        raise HTTPException(status_code=500, detail=f"Database unavailable: {exc}")

    user = db.get_user_by_email(db_path, body.email)

    try:
        password_ok = user and auth.verify_password(body.password, user["password_hash"])
    except Exception as exc:
        log.exception("login: password verification failed")
        raise HTTPException(status_code=500, detail=f"Authentication error: {exc}")

    if not password_ok:
        raise HTTPException(status_code=401, detail="Invalid email or password")

    token = auth.create_token(user["id"], user["email"])
    safe_user = {k: v for k, v in user.items() if k != "password_hash"}

    return {"token": token, "user": safe_user}


@app.get("/auth/me")
async def me(current_user: dict = Depends(auth.get_current_user)):
    safe_user = {k: v for k, v in current_user.items() if k != "password_hash"}
    return safe_user


# ── Billing routes ────────────────────────────────────────────────────────────

@app.get("/billing/plans")
async def get_plans():
    return billing.PLANS


@app.post("/billing/checkout")
async def create_checkout(
    body: CheckoutRequest,
    current_user: dict = Depends(auth.get_current_user),
):
    if not billing.stripe_enabled():
        raise HTTPException(status_code=503, detail="Billing is not configured")

    origin = os.environ.get("FRONTEND_URL", "http://localhost:5173")
    success_url = f"{origin}/billing?success=true"
    cancel_url = f"{origin}/pricing"

    try:
        url = billing.create_checkout_session(
            current_user, body.plan, success_url, cancel_url
        )
    except ValueError as exc:
        raise HTTPException(status_code=400, detail=str(exc))
    except Exception as exc:
        log.exception("Stripe checkout error")
        raise HTTPException(status_code=500, detail="Failed to create checkout session")

    return {"url": url}


@app.get("/billing/portal")
async def billing_portal(current_user: dict = Depends(auth.get_current_user)):
    if not billing.stripe_enabled():
        raise HTTPException(status_code=503, detail="Billing is not configured")

    customer_id = current_user.get("stripe_customer_id")
    if not customer_id:
        raise HTTPException(status_code=400, detail="No billing account found. Please subscribe first.")

    origin = os.environ.get("FRONTEND_URL", "http://localhost:5173")
    return_url = f"{origin}/billing"

    try:
        url = billing.create_portal_session(customer_id, return_url)
    except Exception as exc:
        log.exception("Stripe portal error")
        raise HTTPException(status_code=500, detail="Failed to create portal session")

    return {"url": url}


@app.get("/billing/status")
async def billing_status(current_user: dict = Depends(auth.get_current_user)):
    return billing.get_subscription_status(current_user)


@app.post("/billing/webhook")
async def stripe_webhook(request: Request):
    payload = await request.body()
    sig = request.headers.get("stripe-signature", "")

    if not billing.stripe_enabled():
        raise HTTPException(status_code=503, detail="Billing not configured")

    try:
        billing.handle_webhook(payload, sig)
    except ValueError as exc:
        raise HTTPException(status_code=400, detail=str(exc))
    except Exception as exc:
        log.exception("Webhook handling error")
        raise HTTPException(status_code=500, detail="Webhook processing failed")

    return {"received": True}


@app.post("/webhook/stripe")
async def stripe_webhook_v2(request: Request):
    payload = await request.body()
    sig = request.headers.get("stripe-signature", "")

    if not billing.stripe_enabled():
        raise HTTPException(status_code=503, detail="Billing not configured")

    try:
        billing.handle_webhook(payload, sig)
    except ValueError as exc:
        raise HTTPException(status_code=400, detail=str(exc))
    except Exception as exc:
        log.exception("Webhook handling error")
        raise HTTPException(status_code=500, detail="Webhook processing failed")

    return {"received": True}


# ── WebSocket chat endpoint ───────────────────────────────────────────────────

@app.websocket("/chat")
async def chat_endpoint(websocket: WebSocket, token: str = Query(None)):
    await websocket.accept()

    if history is None:
        await websocket.send_json({"type": "error", "message": "Server still initialising"})
        await websocket.send_json({"type": "done"})
        await websocket.close()
        return

    # Auth check — required if REQUIRE_AUTH=1 env var is set, optional otherwise (dev compat)
    current_user: dict | None = None
    if _REQUIRE_AUTH or token:
        if not token:
            await websocket.send_json({"type": "error", "message": "Authentication required"})
            await websocket.send_json({"type": "done"})
            await websocket.close()
            return

        payload = auth.verify_token(token)
        if not payload:
            await websocket.send_json({"type": "error", "message": "Invalid or expired token"})
            await websocket.send_json({"type": "done"})
            await websocket.close()
            return

        db_path = db.get_db_path()
        current_user = db.get_user_by_id(db_path, payload.get("sub", ""))
        if not current_user:
            # Token is cryptographically valid — DB record missing (e.g. after redeploy).
            # Reconstruct a minimal user from the token payload so chat still works.
            current_user = {
                "id": payload.get("sub", ""),
                "email": payload.get("email", ""),
                "subscription_status": "free",
                "subscription_plan": None,
            }

    # Usage / subscription check
    if current_user:
        db_path = db.get_db_path()
        status_info = billing.get_subscription_status(current_user)
        limit = status_info.get("messages_limit")
        if limit is not None and status_info["messages_used"] >= limit:
            await websocket.send_json({
                "type": "error",
                "message": (
                    f"You've reached the free limit of {billing.FREE_LIMIT} messages. "
                    "Upgrade to Pro for unlimited messages at /pricing"
                ),
            })
            await websocket.send_json({"type": "done"})
            await websocket.close()
            return

    try:
        data = await websocket.receive_json()
        prompt = data.get("prompt", "").strip()
        session_id = data.get("session_id")
        image = data.get("image")  # optional: {data: base64str, media_type: str}

        if not prompt and not image:
            await websocket.send_json({"type": "error", "message": "prompt is required"})
            await websocket.send_json({"type": "done"})
            await websocket.close()
            return

        # Validate image payload if present
        if image and (not isinstance(image, dict) or not image.get("data") or not image.get("media_type")):
            image = None

        async def send(msg: dict):
            await websocket.send_json(msg)

        await run_turn_stream(prompt, session_id, send, history, user_id=current_user["id"] if current_user else None, image=image)

        # Increment usage after successful response
        if current_user:
            month = datetime.now(timezone.utc).strftime("%Y-%m")
            db.increment_usage(db.get_db_path(), current_user["id"], month)

        await websocket.close()

    except WebSocketDisconnect:
        pass
    except Exception as exc:
        try:
            await websocket.send_json({"type": "error", "message": str(exc)})
            await websocket.send_json({"type": "done"})
            await websocket.close()
        except Exception:
            pass


# ── Admin endpoints ───────────────────────────────────────────────────────────

@app.post("/admin/set-enterprise")
async def admin_set_enterprise(
    body: SetEnterpriseRequest,
    x_admin_secret: str = Header(None, alias="X-Admin-Secret"),
):
    admin_secret = os.environ.get("ADMIN_SECRET", "").strip()
    if not admin_secret or x_admin_secret != admin_secret:
        raise HTTPException(status_code=403, detail="Invalid or missing admin secret")

    db_path = db.get_db_path()
    user = db.get_user_by_email(db_path, body.email)
    if not user:
        raise HTTPException(status_code=404, detail=f"No user found with email {body.email!r}")

    db.update_user(
        db_path, user["id"],
        subscription_plan="enterprise",
        subscription_status="active",
    )
    log.info("admin_set_enterprise: set %s to enterprise", body.email)
    return {"ok": True, "email": body.email, "plan": "enterprise", "status": "active"}


# ── Tasks endpoints ───────────────────────────────────────────────────────────

@app.get("/tasks")
async def get_tasks(current_user: dict = Depends(auth.get_current_user)):
    is_admin = bool(current_user.get("is_admin", 0))
    plan = current_user.get("subscription_plan")
    status = current_user.get("subscription_status", "free")
    if not (is_admin or (status == "active" and plan == "enterprise")):
        raise HTTPException(status_code=403, detail="Enterprise plan required")
    db_path = db.get_db_path()
    return db.get_tasks_for_user(db_path, current_user["id"])


# ── Existing REST endpoints ───────────────────────────────────────────────────

@app.get("/sessions")
async def get_sessions():
    if history is None:
        return []
    return history.list_sessions()


@app.get("/history/{session_id}")
async def get_history(session_id: str):
    if history is None:
        raise HTTPException(status_code=503, detail="Server still initialising")
    try:
        return history.get_transcript(session_id)
    except Exception as exc:
        raise HTTPException(status_code=500, detail=str(exc))


@app.get("/tunnel-url")
async def tunnel_url_endpoint():
    return {"url": get_tunnel_url()}


@app.post("/export")
async def export_document(body: ExportRequest):
    if body.format == "pdf":
        file_bytes = generate_pdf(body.text, body.title)
        media_type = "application/pdf"
        filename = f"{slugify(body.title)}.pdf"
    elif body.format == "docx":
        file_bytes = generate_docx(body.text, body.title)
        media_type = "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
        filename = f"{slugify(body.title)}.docx"
    else:
        raise HTTPException(status_code=400, detail="format must be pdf or docx")
    return Response(
        content=file_bytes,
        media_type=media_type,
        headers={"Content-Disposition": f'attachment; filename="{filename}"'},
    )


@app.get("/download/{filename}")
async def download_file(filename: str):
    import tempfile
    _railway = bool(os.environ.get("RAILWAY_ENVIRONMENT") or os.environ.get("RAILWAY_PROJECT_ID"))
    downloads_dir = pathlib.Path("/data/downloads" if _railway else tempfile.gettempdir()) / "zeus_downloads"
    file_path = downloads_dir / filename
    # Prevent path traversal
    if not file_path.resolve().is_relative_to(downloads_dir.resolve()):
        raise HTTPException(status_code=400, detail="Invalid filename")
    if not file_path.exists():
        raise HTTPException(status_code=404, detail="File not found or expired")
    display_name = filename.split("_", 1)[-1] if "_" in filename else filename
    return Response(
        content=file_path.read_bytes(),
        media_type="application/zip",
        headers={
            "Content-Disposition": f'attachment; filename="{display_name}"',
            "Content-Length": str(file_path.stat().st_size),
        },
    )


@app.get("/sitemap.xml", include_in_schema=False)
async def sitemap():
    path = pathlib.Path(__file__).parent / "sitemap.xml"
    return Response(content=path.read_text(encoding="utf-8"), media_type="application/xml")


@app.get("/health")
async def health():
    log.info("GET /health — ok")
    return {"status": "ok"}


# Serve built React app from web/dist/ at root (lazy import — aiofiles not required on Railway)
_dist = pathlib.Path(__file__).parent.parent / "web" / "dist"
if _dist.exists():
    from fastapi.staticfiles import StaticFiles
    app.mount("/", StaticFiles(directory=str(_dist), html=True), name="static")


if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000, reload=False)
