import asyncio
import httpx
import json
import logging
import os
import pathlib
import subprocess
import sys
import traceback
import uuid
from contextlib import asynccontextmanager
from datetime import datetime, timezone

# Log to stderr immediately — before basicConfig — so Railway captures startup
# crashes even if the import chain below fails.
print("zeus main.py: starting imports", file=sys.stderr, flush=True)

from fastapi import Depends, FastAPI, File, Header, HTTPException, Query, Request, UploadFile, WebSocket, WebSocketDisconnect
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import FileResponse, HTMLResponse, JSONResponse, Response
from pydantic import BaseModel, Field

print("zeus main.py: fastapi ok", file=sys.stderr, flush=True)

from zeus_agent import HistoryStore, get_anthropic_client, run_turn_stream

print("zeus main.py: zeus_agent ok", file=sys.stderr, flush=True)

from tunnel import get_tunnel_url, start_tunnel_background, stop_tunnel

import db
import auth
import billing
import did_uploader
import scheduler as _scheduler_mod
import webhooks as _webhooks_mod
import youtube_uploader

import io
import re as _re

from fpdf import FPDF
from docx import Document as DocxDocument
from docx.oxml import OxmlElement


def slugify(text: str) -> str:
    text = text.lower()
    text = _re.sub(r'[^a-z0-9\s-]', '', text)
    text = _re.sub(r'[\s-]+', '-', text).strip('-')
    return text[:60]


def generate_pdf(text: str, title: str) -> bytes:
    pdf = FPDF()
    pdf.add_page()
    pdf.set_margins(20, 20, 20)

    # Title
    pdf.set_font("Helvetica", style="B", size=18)
    pdf.cell(0, 12, title, align="C", new_x="LMARGIN", new_y="NEXT")

    # Horizontal rule
    pdf.set_draw_color(180, 180, 180)
    pdf.set_line_width(0.5)
    pdf.line(20, pdf.get_y(), 190, pdf.get_y())
    pdf.ln(4)

    # Body
    pdf.set_font("Helvetica", size=11)
    pdf.set_text_color(30, 30, 30)
    for para in text.split("\n\n"):
        para = para.strip()
        if not para:
            continue
        pdf.multi_cell(0, 6, para)
        pdf.ln(4)

    # Footer
    pdf.set_y(-15)
    pdf.set_font("Helvetica", size=8)
    pdf.set_text_color(150, 150, 150)
    pdf.cell(0, 5, "Generated by Zeus \u00b7 zeusaidesign.com", align="C")

    return bytes(pdf.output())


def generate_docx(text: str, title: str) -> bytes:
    doc = DocxDocument()

    # Title as Heading 1
    doc.add_heading(title, level=1)

    # Body — double-newline = paragraph, single-newline = line break within paragraph
    for para_text in text.split("\n\n"):
        para_text = para_text.strip()
        if not para_text:
            continue
        lines = para_text.split("\n")
        para = doc.add_paragraph(lines[0])
        for line in lines[1:]:
            # Word line break must be in its own run before the text run
            br_run = para.add_run()
            br = OxmlElement("w:br")
            br_run._r.append(br)
            para.add_run(line)

    buf = io.BytesIO()
    doc.save(buf)
    return buf.getvalue()


def _send_task_email(
    user_email: str,
    description: str,
    live_url: str | None,
    result: str,
) -> None:
    """Send a task completion email via Gmail SMTP. Silently skips if not configured."""
    import smtplib
    from email.mime.multipart import MIMEMultipart
    from email.mime.text import MIMEText

    smtp_email = os.environ.get("SMTP_EMAIL", "").strip()
    smtp_password = os.environ.get("SMTP_PASSWORD", "").strip()
    if not smtp_email or not smtp_password:
        log.warning("_send_task_email: SMTP_EMAIL/SMTP_PASSWORD not set — skipping")
        return

    subject = f"Zeus: Your background task is complete — {description}"
    body = "\n".join([
        "Your background task has finished.",
        "",
        f"Task: {description}",
        f"Live URL: {live_url or 'See result below'}",
        "",
        "Result:",
        result[:2000],
        "",
        "— Zeus AI Design",
        "zeusaidesign.com",
    ])

    msg = MIMEMultipart()
    msg["From"] = smtp_email
    msg["To"] = user_email
    msg["Subject"] = subject
    msg.attach(MIMEText(body, "plain"))

    try:
        with smtplib.SMTP_SSL("smtp.gmail.com", 465, timeout=20) as server:
            server.login(smtp_email, smtp_password)
            server.sendmail(smtp_email, [user_email], msg.as_string())
        log.info("_send_task_email: sent to %s", user_email)
    except smtplib.SMTPAuthenticationError:
        log.warning("_send_task_email: Gmail auth failed — check SMTP_PASSWORD is an App Password")
    except smtplib.SMTPException as exc:
        log.warning("_send_task_email: SMTP error: %s", exc)


_RAILWAY = bool(os.environ.get("RAILWAY_ENVIRONMENT") or os.environ.get("RAILWAY_PROJECT_ID"))
_REQUIRE_AUTH = os.environ.get("REQUIRE_AUTH", "").strip() == "1"

print("zeus main.py: tunnel ok", file=sys.stderr, flush=True)

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
)
log = logging.getLogger("zeus")

# Log installed packages once so Railway deploy logs show the exact environment.
try:
    import importlib.metadata as _meta
    _pkgs = {d.metadata["Name"]: d.version for d in _meta.distributions()}
    for _name in ("fastapi", "starlette", "uvicorn", "anthropic", "httpx", "anyio"):
        log.info("pkg %s==%s", _name, _pkgs.get(_name, "NOT INSTALLED"))
except Exception:
    log.exception("could not enumerate installed packages")

history: HistoryStore | None = None
_background_tasks: set = set()

_parse_cache: dict[str, dict] = {}

_SCHEDULED_TASK_LIMITS = {"pro": 5, "agency": 20, "enterprise": None}


def _scheduled_task_plan_allowed(user: dict) -> bool:
    """Return True if user's plan includes scheduled tasks."""
    plan = user.get("subscription_plan")
    status = user.get("subscription_status", "free")
    is_admin = bool(user.get("is_admin", 0))
    return is_admin or (status == "active" and plan in _SCHEDULED_TASK_LIMITS)


def _scheduled_task_limit(user: dict) -> int | None:
    """Return max active scheduled tasks for user's plan, or None for unlimited."""
    if user.get("is_admin"):
        return None
    return _SCHEDULED_TASK_LIMITS.get(user.get("subscription_plan"))


_WEBSITE_LIMITS: dict[str, int | None] = {
    "free":       0,
    "pro":        1,
    "agency":     5,
    "enterprise": None,
}


def _website_limit(user: dict) -> int | None:
    """Return max websites for user's plan, or None for unlimited. Admins unlimited."""
    if user.get("is_admin"):
        return None
    plan = user.get("subscription_plan")
    status = user.get("subscription_status", "free")
    if status != "active":
        return 0
    return _WEBSITE_LIMITS.get(plan, 0)


@asynccontextmanager
async def lifespan(app: FastAPI):
    global history
    log.info("Startup: initialising HistoryStore")
    try:
        history = HistoryStore()
        log.info("HistoryStore ready at %s", history.dir)
    except Exception:
        log.exception("FATAL: HistoryStore init failed")
        raise

    # Initialise user tables in the same DB file
    try:
        _db_path = db.get_db_path()
        db.init_user_tables(_db_path)
        log.info("User tables initialised at %s", _db_path)
        db.fail_stale_tasks(_db_path)
        log.info("Stale running tasks marked as failed")
        # Ensure owner account always has enterprise + admin access
        _owner_email = "dominic.rowle@yahoo.com"
        _owner = db.get_user_by_email(_db_path, _owner_email)
        if _owner:
            db.update_user(_db_path, _owner["id"],
                           subscription_plan="enterprise",
                           subscription_status="active",
                           is_admin=1)
            log.info("Owner account %s set to enterprise/admin", _owner_email)
        else:
            log.info("Owner account %s not yet registered — will be promoted on first login", _owner_email)
    except Exception:
        log.exception("FATAL: user table init failed")
        raise

    # Ensure persistent storage directories exist for avatars and D-ID videos
    for _d in ("/data/avatars", "/data/videos"):
        pathlib.Path(_d).mkdir(parents=True, exist_ok=True)
    log.info("Storage directories ready: /data/avatars, /data/videos")

    api_key_set = bool(os.environ.get("ANTHROPIC_API_KEY", "").strip())
    log.info("ANTHROPIC_API_KEY present: %s", api_key_set)
    if not api_key_set:
        raise RuntimeError("ANTHROPIC_API_KEY is not set — add it to Railway → Service → Variables")
    get_anthropic_client()  # validate key and warm up client at startup
    log.info("Anthropic client initialised")
    try:
        _scheduler_mod.init_scheduler(history)
        log.info("Scheduler initialised")
        if _RAILWAY:
            log.info("Running on Railway — skipping cloudflared tunnel (not installed)")
            yield
        else:
            port = int(os.environ.get("PORT", 8000))
            task = asyncio.create_task(start_tunnel_background(port))
            _background_tasks.add(task)
            task.add_done_callback(_background_tasks.discard)
            yield
            task.cancel()
            stop_tunnel()
    finally:
        _scheduler_mod.shutdown_scheduler()
        log.info("Scheduler shut down")


app = FastAPI(lifespan=lifespan)
app.include_router(_webhooks_mod.router)


@app.exception_handler(Exception)
async def unhandled_exception_handler(request: Request, exc: Exception):
    log.exception("Unhandled error on %s %s", request.method, request.url.path)
    return JSONResponse(
        status_code=500,
        content={"detail": "Internal server error"},
    )


app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)


# ── Pydantic request models ───────────────────────────────────────────────────

class RegisterRequest(BaseModel):
    email: str
    password: str
    name: str
    tc_accepted: bool


class LoginRequest(BaseModel):
    email: str
    password: str


class CheckoutRequest(BaseModel):
    plan: str


class SetEnterpriseRequest(BaseModel):
    email: str


class AdminUserPatchRequest(BaseModel):
    field: str   # "subscription_plan" or "subscription_status"
    value: str


class ExportRequest(BaseModel):
    text: str = Field(max_length=100_000)
    format: str   # "pdf" or "docx"
    title: str
    doc_type: str


class LinkWebsiteRequest(BaseModel):
    netlify_site_name: str
    client_name: str | None = None


class UpdateWebsiteRequest(BaseModel):
    client_name: str | None = None
    sync_files: bool = False


# ── Auth routes ───────────────────────────────────────────────────────────────

@app.post("/auth/register")
async def register(body: RegisterRequest):
    if not body.tc_accepted:
        raise HTTPException(status_code=400, detail="You must accept the Terms & Conditions")

    if not body.email or "@" not in body.email:
        raise HTTPException(status_code=400, detail="Invalid email address")

    if len(body.password) < 8:
        raise HTTPException(status_code=400, detail="Password must be at least 8 characters")

    try:
        db_path = db.get_db_path()
    except Exception as exc:
        log.exception("register: failed to get DB path")
        raise HTTPException(status_code=500, detail=f"Database unavailable: {exc}")

    existing = db.get_user_by_email(db_path, body.email)
    if existing:
        raise HTTPException(status_code=409, detail="An account with that email already exists")

    try:
        password_hash = auth.hash_password(body.password)
    except Exception as exc:
        log.exception("register: password hashing failed")
        raise HTTPException(status_code=500, detail=f"Password hashing failed: {exc}")

    tc_accepted_at = datetime.now(timezone.utc).isoformat()

    try:
        user = db.create_user(
            db_path,
            email=body.email,
            password_hash=password_hash,
            name=body.name.strip(),
            tc_accepted_at=tc_accepted_at,
        )
    except Exception as exc:
        log.exception("register: create_user failed")
        raise HTTPException(status_code=500, detail=f"Could not create account: {exc}")

    # Create Stripe customer if Stripe is enabled
    if billing.stripe_enabled():
        customer_id = billing.create_stripe_customer(user)
        if customer_id:
            db.update_user(db_path, user["id"], stripe_customer_id=customer_id)
            user = db.get_user_by_id(db_path, user["id"])

    token = auth.create_token(user["id"], user["email"], is_admin=bool(user.get("is_admin", 0)))
    safe_user = {k: v for k, v in user.items() if k != "password_hash"}

    return {"token": token, "user": safe_user}


@app.post("/auth/login")
async def login(body: LoginRequest):
    try:
        db_path = db.get_db_path()
    except Exception as exc:
        log.exception("login: failed to get DB path")
        raise HTTPException(status_code=500, detail=f"Database unavailable: {exc}")

    user = db.get_user_by_email(db_path, body.email)

    try:
        password_ok = user and auth.verify_password(body.password, user["password_hash"])
    except Exception as exc:
        log.exception("login: password verification failed")
        raise HTTPException(status_code=500, detail=f"Authentication error: {exc}")

    if not password_ok:
        raise HTTPException(status_code=401, detail="Invalid email or password")

    token = auth.create_token(user["id"], user["email"], is_admin=bool(user.get("is_admin", 0)))
    safe_user = {k: v for k, v in user.items() if k != "password_hash"}

    return {"token": token, "user": safe_user}


@app.get("/auth/me")
async def me(current_user: dict = Depends(auth.get_current_user)):
    safe_user = {k: v for k, v in current_user.items() if k != "password_hash"}
    return safe_user


# ── Billing routes ────────────────────────────────────────────────────────────

@app.get("/billing/plans")
async def get_plans():
    return billing.PLANS


@app.post("/billing/checkout")
async def create_checkout(
    body: CheckoutRequest,
    current_user: dict = Depends(auth.get_current_user),
):
    if not billing.stripe_enabled():
        raise HTTPException(status_code=503, detail="Billing is not configured")

    origin = os.environ.get("FRONTEND_URL", "http://localhost:5173")
    success_url = f"{origin}/billing?success=true"
    cancel_url = f"{origin}/pricing"

    try:
        url = billing.create_checkout_session(
            current_user, body.plan, success_url, cancel_url
        )
    except ValueError as exc:
        raise HTTPException(status_code=400, detail=str(exc))
    except Exception as exc:
        log.exception("Stripe checkout error")
        raise HTTPException(status_code=500, detail="Failed to create checkout session")

    return {"url": url}


@app.get("/billing/portal")
async def billing_portal(current_user: dict = Depends(auth.get_current_user)):
    if not billing.stripe_enabled():
        raise HTTPException(status_code=503, detail="Billing is not configured")

    customer_id = current_user.get("stripe_customer_id")
    if not customer_id:
        raise HTTPException(status_code=400, detail="No billing account found. Please subscribe first.")

    origin = os.environ.get("FRONTEND_URL", "http://localhost:5173")
    return_url = f"{origin}/billing"

    try:
        url = billing.create_portal_session(customer_id, return_url)
    except Exception as exc:
        log.exception("Stripe portal error")
        raise HTTPException(status_code=500, detail="Failed to create portal session")

    return {"url": url}


@app.get("/billing/status")
async def billing_status(current_user: dict = Depends(auth.get_current_user)):
    return billing.get_subscription_status(current_user)


@app.post("/billing/webhook")
async def stripe_webhook(request: Request):
    payload = await request.body()
    sig = request.headers.get("stripe-signature", "")

    if not billing.stripe_enabled():
        raise HTTPException(status_code=503, detail="Billing not configured")

    try:
        billing.handle_webhook(payload, sig)
    except ValueError as exc:
        raise HTTPException(status_code=400, detail=str(exc))
    except Exception as exc:
        log.exception("Webhook handling error")
        raise HTTPException(status_code=500, detail="Webhook processing failed")

    return {"received": True}


@app.post("/webhook/stripe")
async def stripe_webhook_v2(request: Request):
    payload = await request.body()
    sig = request.headers.get("stripe-signature", "")

    if not billing.stripe_enabled():
        raise HTTPException(status_code=503, detail="Billing not configured")

    try:
        billing.handle_webhook(payload, sig)
    except ValueError as exc:
        raise HTTPException(status_code=400, detail=str(exc))
    except Exception as exc:
        log.exception("Webhook handling error")
        raise HTTPException(status_code=500, detail="Webhook processing failed")

    return {"received": True}


# ── WebSocket chat endpoint ───────────────────────────────────────────────────

@app.websocket("/chat")
async def chat_endpoint(websocket: WebSocket, token: str = Query(None)):
    await websocket.accept()

    if history is None:
        await websocket.send_json({"type": "error", "message": "Server still initialising"})
        await websocket.send_json({"type": "done"})
        await websocket.close()
        return

    # Auth check — required if REQUIRE_AUTH=1 env var is set, optional otherwise (dev compat)
    current_user: dict | None = None
    if _REQUIRE_AUTH or token:
        if not token:
            await websocket.send_json({"type": "error", "message": "Authentication required"})
            await websocket.send_json({"type": "done"})
            await websocket.close()
            return

        payload = auth.verify_token(token)
        if not payload:
            await websocket.send_json({"type": "error", "message": "Invalid or expired token"})
            await websocket.send_json({"type": "done"})
            await websocket.close()
            return

        db_path = db.get_db_path()
        current_user = db.get_user_by_id(db_path, payload.get("sub", ""))
        if not current_user:
            # Token is cryptographically valid — DB record missing (e.g. after redeploy).
            # Reconstruct a minimal user from the token payload so chat still works.
            current_user = {
                "id": payload.get("sub", ""),
                "email": payload.get("email", ""),
                "subscription_status": "free",
                "subscription_plan": None,
            }

    # Usage / subscription check
    if current_user:
        db_path = db.get_db_path()
        status_info = billing.get_subscription_status(current_user)
        limit = status_info.get("messages_limit")
        if limit is not None and status_info["messages_used"] >= limit:
            await websocket.send_json({
                "type": "error",
                "message": (
                    f"You've reached the free limit of {billing.FREE_LIMIT} messages. "
                    "Upgrade to Pro for unlimited messages at /pricing"
                ),
            })
            await websocket.send_json({"type": "done"})
            await websocket.close()
            return

    try:
        data = await websocket.receive_json()
        prompt = data.get("prompt", "").strip()
        session_id = data.get("session_id")
        image = data.get("image")  # optional: {data: base64str, media_type: str}

        if not prompt and not image:
            await websocket.send_json({"type": "error", "message": "prompt is required"})
            await websocket.send_json({"type": "done"})
            await websocket.close()
            return

        # Validate image payload if present
        if image and (not isinstance(image, dict) or not image.get("data") or not image.get("media_type")):
            image = None

        async def send(msg: dict):
            await websocket.send_json(msg)

        await run_turn_stream(prompt, session_id, send, history, user_id=current_user["id"] if current_user else None, image=image)

        # Increment usage after successful response
        if current_user:
            month = datetime.now(timezone.utc).strftime("%Y-%m")
            db.increment_usage(db.get_db_path(), current_user["id"], month)

        await websocket.close()

    except WebSocketDisconnect:
        pass
    except Exception as exc:
        try:
            await websocket.send_json({"type": "error", "message": str(exc)})
            await websocket.send_json({"type": "done"})
            await websocket.close()
        except Exception:
            pass


# ── Admin endpoints ───────────────────────────────────────────────────────────

@app.post("/admin/set-enterprise")
async def admin_set_enterprise(
    body: SetEnterpriseRequest,
    x_admin_secret: str = Header(None, alias="X-Admin-Secret"),
):
    admin_secret = os.environ.get("ADMIN_SECRET", "").strip()
    if not admin_secret or x_admin_secret != admin_secret:
        raise HTTPException(status_code=403, detail="Invalid or missing admin secret")

    db_path = db.get_db_path()
    user = db.get_user_by_email(db_path, body.email)
    if not user:
        raise HTTPException(status_code=404, detail=f"No user found with email {body.email!r}")

    db.update_user(
        db_path, user["id"],
        subscription_plan="enterprise",
        subscription_status="active",
    )
    log.info("admin_set_enterprise: set %s to enterprise", body.email)
    return {"ok": True, "email": body.email, "plan": "enterprise", "status": "active"}


@app.get("/admin/users")
async def admin_list_users(current_user: dict = Depends(auth.get_current_user)):
    if not current_user.get("is_admin"):
        raise HTTPException(status_code=403, detail="Admin access required")
    db_path = db.get_db_path()
    log.info("admin_list_users: querying db at %s", db_path)
    users = db.get_all_users(db_path)
    log.info("admin_list_users: get_all_users returned %d row(s): %s",
             len(users), [u.get("email") for u in users])
    month = datetime.now(timezone.utc).strftime("%Y-%m")
    for u in users:
        u.pop("password_hash", None)
        u["messages_this_month"] = db.get_monthly_usage(db_path, u["id"], month)
    return users


_ALLOWED_ADMIN_FIELDS = {
    "subscription_plan": {"free", "pro", "agency", "enterprise"},
    "subscription_status": {"free", "active", "cancelled"},
}


@app.patch("/admin/users/{user_id}")
async def admin_patch_user(
    user_id: str,
    body: AdminUserPatchRequest,
    current_user: dict = Depends(auth.get_current_user),
):
    if not current_user.get("is_admin"):
        raise HTTPException(status_code=403, detail="Admin access required")
    allowed_values = _ALLOWED_ADMIN_FIELDS.get(body.field)
    if allowed_values is None:
        raise HTTPException(status_code=400, detail=f"Field '{body.field}' is not editable")
    if body.value not in allowed_values:
        raise HTTPException(
            status_code=400,
            detail=f"Value '{body.value}' not allowed for '{body.field}'. Allowed: {sorted(allowed_values)}",
        )
    db_path = db.get_db_path()
    target = db.get_user_by_id(db_path, user_id)
    if not target:
        raise HTTPException(status_code=404, detail="User not found")
    db.update_user(db_path, user_id, **{body.field: body.value})
    log.info("admin_patch_user: set %s.%s = %s (by admin %s)", user_id, body.field, body.value, current_user["id"])
    return {"ok": True}


@app.get("/admin/tasks")
async def admin_list_tasks(current_user: dict = Depends(auth.get_current_user)):
    if not current_user.get("is_admin"):
        raise HTTPException(status_code=403, detail="Admin access required")
    db_path = db.get_db_path()
    db.init_user_tables(db_path)
    return db.get_all_tasks(db_path)


@app.get("/admin/credits")
async def admin_credits(current_user: dict = Depends(auth.get_current_user)):
    if not current_user.get("is_admin"):
        raise HTTPException(status_code=403, detail="Admin access required")
    api_key = os.environ.get("ANTHROPIC_API_KEY", "").strip()
    if not api_key:
        return {"balance": None, "message": "Balance unavailable"}
    try:
        async with httpx.AsyncClient() as client:
            resp = await client.get(
                "https://api.anthropic.com/v1/organizations/credits/balance",
                headers={
                    "x-api-key": api_key,
                    "anthropic-version": "2023-06-01",
                },
                timeout=10,
            )
        if resp.status_code != 200:
            return {"balance": None, "message": "Balance unavailable"}
        data = resp.json()
        # Response shape: {"balance": {"available": [{"amount": 1234, "currency": "USD"}]}}
        available = data.get("balance", {}).get("available", [])
        if available:
            amount_cents = available[0].get("amount", 0)
            currency = available[0].get("currency", "USD")
            return {"balance": round(amount_cents / 100, 2), "currency": currency}
        return {"balance": None, "message": "Balance unavailable"}
    except Exception:
        log.exception("admin_credits: failed to fetch Anthropic balance")
        return {"balance": None, "message": "Balance unavailable"}


@app.post("/admin/test-song-pipeline")
async def admin_test_song_pipeline(current_user: dict = Depends(auth.get_current_user)):
    if not current_user.get("is_admin"):
        raise HTTPException(status_code=403, detail="Admin access required")

    import lyrics as _lyrics_mod
    import songs as _songs_mod
    from song_genres import GENRE_PRESETS as _GENRE_PRESETS

    db_path = db.get_db_path()
    user_id = current_user["id"]

    db.upsert_song_credits(db_path, user_id, balance=10, monthly_allowance=10)
    log.info("admin_test_song_pipeline: granted 10 credits to %s", user_id)

    try:
        lyric_result = _lyrics_mod.generate_lyrics(
            user_id,
            "30-second jingle for a Manchester coffee shop, Friday vibes",
            db_path,
        )
    except Exception as exc:
        log.exception("admin_test_song_pipeline: lyrics generation failed")
        raise HTTPException(status_code=500, detail=f"Lyrics generation failed: {exc}")

    lyric_id = lyric_result["lyric_id"]
    log.info("admin_test_song_pipeline: lyric_id=%s title=%r", lyric_id, lyric_result["title"])

    try:
        variant_result = _songs_mod.generate_song_variant(
            user_id=user_id,
            lyric_id=lyric_id,
            style_prompt=_GENRE_PRESETS["pop"],
            genre_tag="pop",
            db_path=db_path,
        )
    except Exception as exc:
        log.exception("admin_test_song_pipeline: variant submission failed")
        raise HTTPException(status_code=500, detail=f"Variant submission failed: {exc}")

    variant_row = db.get_song_variant_by_id(db_path, variant_result["variant_id"])
    log.info("admin_test_song_pipeline: variant_id=%s task_id=%s",
             variant_result["variant_id"], variant_row["provider_job_id"] if variant_row else None)

    return {
        "lyric_id": lyric_id,
        "variant_id": variant_result["variant_id"],
        "task_id": variant_row["provider_job_id"] if variant_row else None,
        "message": "Submitted to Apiframe. Webhook should fire in 30-90s.",
    }


# ── Song API endpoints ───────────────────────────────────────────────────────

class SongsGenerateRequest(BaseModel):
    brief: str = Field(min_length=1, max_length=2000)
    genres: list[str] = Field(min_length=1, max_length=7)
    # Advanced generation controls (all optional)
    vocal_gender: str | None = None      # "m" or "f" → sunoParams.vocal_gender
    creativity: float | None = None      # 0.0–1.0 → sunoParams.weirdness_constraint
    style_weight: float | None = None    # 0.0–1.0 → sunoParams.style_weight
    tempo: str | None = None             # "slow" | "medium" | "fast" | "custom"
    tempo_bpm: int | None = None         # used when tempo == "custom"
    model_version: str | None = None     # "V4.5" | "V4.5 Plus" | "V5" | "V5.5"
    accent: str | None = None            # e.g. "British" → appended to style string
    explicit: bool = False               # agency/enterprise only — loosens Suno content filter
    inspired_by_descriptors: str | None = None  # from /api/songs/artist-style


@app.post("/api/songs/generate")
async def songs_generate(
    body: SongsGenerateRequest,
    current_user: dict = Depends(auth.get_current_user),
):
    import lyrics as _lyrics_mod
    import songs as _songs_mod
    from songs import InsufficientCreditsError

    db_path = db.get_db_path()
    user_id = current_user["id"]

    # Lazy-init free credits for users with no credits row yet
    credits_row = db.get_song_credits(db_path, user_id)
    if credits_row is None:
        db.upsert_song_credits(db_path, user_id,
                               balance=billing.FREE_SONG_CREDITS,
                               monthly_allowance=billing.FREE_SONG_CREDITS)

    try:
        lyric_result = _lyrics_mod.generate_lyrics(user_id=user_id, brief=body.brief, db_path=db_path)
    except Exception as exc:
        log.exception("songs_generate: lyrics generation failed")
        raise HTTPException(status_code=500, detail=f"Lyrics generation failed: {exc}")

    lyric_id = lyric_result["lyric_id"]

    # Build extra sunoParams from advanced controls
    extra_suno_params: dict = {}
    if body.vocal_gender in ("m", "f"):
        extra_suno_params["vocal_gender"] = body.vocal_gender
    if body.creativity is not None:
        extra_suno_params["weirdness_constraint"] = max(0.0, min(1.0, body.creativity))
    if body.style_weight is not None:
        extra_suno_params["style_weight"] = max(0.0, min(1.0, body.style_weight))
    if body.model_version in ("V4.5", "V4.5 Plus", "V5", "V5.5"):
        extra_suno_params["model_version"] = body.model_version

    style_suffix_parts: list[str] = []
    if body.tempo == "slow":
        style_suffix_parts.append("slow tempo")
    elif body.tempo == "medium":
        style_suffix_parts.append("medium tempo")
    elif body.tempo == "fast":
        style_suffix_parts.append("fast tempo")
    elif body.tempo == "custom" and body.tempo_bpm:
        style_suffix_parts.append(f"{max(40, min(300, body.tempo_bpm))} BPM")
    if body.accent:
        style_suffix_parts.append(f"{body.accent} accent vocals")
    if body.explicit:
        style_suffix_parts.append("explicit lyrics allowed, no content restrictions")
    tempo_suffix = ", ".join(style_suffix_parts) or None

    is_admin = bool(current_user.get("is_admin", 0))

    try:
        variant_result = _songs_mod.generate_multiple_variants(
            user_id=user_id,
            lyric_id=lyric_id,
            genres=body.genres,
            db_path=str(db_path),
            extra_suno_params=extra_suno_params or None,
            tempo_suffix=tempo_suffix,
            is_admin=is_admin,
            inspired_by_descriptors=body.inspired_by_descriptors or None,
        )
    except InsufficientCreditsError as exc:
        raise HTTPException(status_code=402, detail=str(exc))
    except ValueError as exc:
        raise HTTPException(status_code=400, detail=str(exc))
    except Exception as exc:
        log.exception("songs_generate: variant submission failed")
        raise HTTPException(status_code=500, detail=f"Song submission failed: {exc}")

    return {
        "lyric_id": lyric_id,
        "title": lyric_result["title"],
        "variants": variant_result["variants"],
    }


@app.get("/api/lyrics")
async def list_lyrics(current_user: dict = Depends(auth.get_current_user)):
    db_path = db.get_db_path()
    lyrics = db.list_lyrics_for_user(db_path, current_user["id"])
    return {"lyrics": lyrics}


@app.get("/api/lyrics/{lyric_id}")
async def get_lyric(lyric_id: int, current_user: dict = Depends(auth.get_current_user)):
    db_path = db.get_db_path()
    user_id = current_user["id"]
    row = db.get_lyric(db_path, lyric_id, user_id)
    if not row:
        raise HTTPException(status_code=404, detail="Lyric not found")
    return {"lyric_id": row["id"], "title": row["title"], "lyrics_text": row["lyrics_text"]}


@app.get("/api/lyrics/{lyric_id}/variants")
async def get_lyric_variants(lyric_id: int, current_user: dict = Depends(auth.get_current_user)):
    db_path = db.get_db_path()
    user_id = current_user["id"]
    lyric = db.get_lyric(db_path, lyric_id, user_id)
    if not lyric:
        raise HTTPException(status_code=404, detail="Lyric not found")
    variants = db.get_song_variants_for_lyric(db_path, lyric_id, user_id)
    return {
        "lyric_id": lyric_id,
        "variants": [
            {
                "variant_id": v["id"],
                "genre_tag": v["genre_tag"],
                "take_number": v["take_number"],
                "status": v["status"],
                "mp3_url": v["mp3_url"],
                "image_url": v["image_url"],
                "duration_seconds": v["duration_seconds"],
                "did_job_id": v.get("did_job_id"),
                "video_url": v.get("video_url"),
                "youtube_url": v.get("youtube_url"),
            }
            for v in (variants or [])
        ],
    }


@app.get("/api/songs/variants/{variant_id}/public")
async def get_song_variant_public(variant_id: int):
    """Public (no auth) endpoint for the share page. Only returns completed variants."""
    db_path = db.get_db_path()
    variant = db.get_song_variant_by_id(db_path, variant_id)
    if not variant or variant.get("status") != "complete":
        raise HTTPException(status_code=404, detail="Song not found")
    title = db.get_lyric_title(db_path, variant["lyric_id"]) or f"Song #{variant_id}"
    return {
        "variant_id": variant["id"],
        "title": title,
        "genre_tag": variant.get("genre_tag"),
        "mp3_url": variant.get("mp3_url"),
        "image_url": variant.get("image_url"),
        "duration_seconds": variant.get("duration_seconds"),
    }


class SongsTopupRequest(BaseModel):
    pack: str


@app.post("/api/songs/topup")
async def songs_topup(
    body: SongsTopupRequest,
    current_user: dict = Depends(auth.get_current_user),
):
    if not billing.stripe_enabled():
        raise HTTPException(status_code=503, detail="Billing is not configured")
    origin = os.environ.get("FRONTEND_URL", "http://localhost:5173")
    success_url = f"{origin}/songs?topup=success"
    cancel_url = f"{origin}/songs"
    try:
        url = billing.create_song_pack_checkout_session(
            current_user, body.pack, success_url, cancel_url
        )
    except ValueError as exc:
        raise HTTPException(status_code=400, detail=str(exc))
    except Exception:
        log.exception("Song pack checkout error")
        raise HTTPException(status_code=500, detail="Failed to create checkout session")
    return {"url": url}


@app.get("/api/users/me/song_credits")
async def get_my_song_credits(current_user: dict = Depends(auth.get_current_user)):
    db_path = db.get_db_path()
    row = db.get_song_credits(db_path, current_user["id"])
    plan = current_user.get("subscription_plan")
    # Derive allowance from the current plan so the banner denominator is always correct,
    # even if the DB monthly_allowance is stale from an earlier credit tier.
    allowance = billing._PLAN_SONG_CREDITS.get(plan, billing.FREE_SONG_CREDITS)
    return {
        "balance": row["balance"] if row else 0,
        "monthly_allowance": allowance,
        "is_admin": bool(current_user.get("is_admin", 0)),
        "plan": plan,
        "youtube_connected": bool(current_user.get("youtube_refresh_token")),
    }


# ── Artist style lookup ──────────────────────────────────────────────────────

class ArtistStyleRequest(BaseModel):
    artist_name: str = Field(min_length=1, max_length=100)


@app.post("/api/songs/artist-style")
async def artist_style(
    body: ArtistStyleRequest,
    current_user: dict = Depends(auth.get_current_user),
):
    """
    Look up an artist's musical style via Serper, then distil to style descriptors
    using Claude Haiku. Returns {"style_descriptors": "comma, separated, list"}.
    """
    serper_key = os.environ.get("SERPER_API_KEY", "").strip()
    if not serper_key:
        raise HTTPException(status_code=503, detail="Artist style lookup not configured (SERPER_API_KEY missing)")

    artist = body.artist_name.strip()
    query = f"{artist} music style genre instruments tempo vocal characteristics"

    try:
        async with httpx.AsyncClient(timeout=15) as client:
            serper_resp = await client.post(
                "https://google.serper.dev/search",
                headers={"X-API-KEY": serper_key, "Content-Type": "application/json"},
                json={"q": query, "num": 5},
            )
        serper_resp.raise_for_status()
        serper_data = serper_resp.json()
    except Exception as exc:
        log.warning("artist_style: Serper call failed for %r: %s", artist, exc)
        raise HTTPException(status_code=502, detail="Style lookup failed — try again")

    snippets = [
        item.get("snippet", "").strip()
        for item in serper_data.get("organic", [])[:3]
        if item.get("snippet", "").strip()
    ]
    if not snippets:
        raise HTTPException(status_code=404, detail=f"No style information found for '{artist}'")

    search_text = "\n".join(snippets)

    try:
        haiku = get_anthropic_client().messages.create(
            model="claude-haiku-4-5-20251001",
            max_tokens=200,
            system=(
                f"Extract 8-12 music style descriptors from these search results about {artist}. "
                "Output ONLY a comma-separated list of descriptors suitable for a music generation "
                "style prompt. Example: reggae, off-beat rhythm guitar, warm bassline, political "
                "lyrics, 80 BPM, Jamaican vocal delivery. Nothing else."
            ),
            messages=[{"role": "user", "content": search_text}],
        )
    except Exception as exc:
        log.exception("artist_style: Haiku call failed for %r", artist)
        raise HTTPException(status_code=500, detail="Style extraction failed — try again")

    descriptors = haiku.content[0].text.strip()
    log.info("artist_style: artist=%r descriptors=%r", artist, descriptors[:80])
    return {"style_descriptors": descriptors}


# ── YouTube OAuth + upload ───────────────────────────────────────────────────

_YOUTUBE_PLANS = {"agency", "enterprise"}

import jwt as _jwt


def _make_yt_state(user_id: str) -> str:
    from datetime import timedelta
    payload = {"sub": user_id, "exp": datetime.now(timezone.utc) + timedelta(minutes=30)}
    return _jwt.encode(payload, auth.SECRET_KEY, algorithm="HS256")


def _decode_yt_state(state: str) -> str | None:
    try:
        payload = _jwt.decode(state, auth.SECRET_KEY, algorithms=["HS256"])
        return payload.get("sub")
    except Exception:
        return None


@app.get("/api/youtube/debug")
async def youtube_debug():
    """Temporary — verify YouTube env vars are present in production."""
    client_id = os.environ.get("GOOGLE_CLIENT_ID", "").strip()
    client_secret = os.environ.get("GOOGLE_CLIENT_SECRET", "").strip()
    return {
        "GOOGLE_CLIENT_ID_first15": client_id[:15] if client_id else "NOT_SET",
        "GOOGLE_CLIENT_SECRET_set": bool(client_secret),
    }


@app.get("/api/youtube/auth")
async def youtube_auth(current_user: dict = Depends(auth.get_current_user)):
    """Redirect the browser to Google's OAuth consent screen."""
    _gid = os.environ.get("GOOGLE_CLIENT_ID", "NOT_SET").strip()
    log.info("youtube_auth: GOOGLE_CLIENT_ID first10=%r", _gid[:10])
    if not youtube_uploader.youtube_enabled():
        raise HTTPException(status_code=503, detail="YouTube integration not configured (GOOGLE_CLIENT_ID/SECRET missing)")

    is_admin = bool(current_user.get("is_admin", 0))
    plan = current_user.get("subscription_plan")
    if not is_admin and plan not in _YOUTUBE_PLANS:
        raise HTTPException(status_code=403, detail="YouTube upload requires Agency plan or above")

    redirect_uri = os.environ.get("YOUTUBE_REDIRECT_URI", "http://localhost:8080/api/youtube/callback")
    log.info("youtube_auth: redirect_uri first30=%r", redirect_uri[:30])
    state = _make_yt_state(current_user["id"])

    try:
        auth_url = youtube_uploader.build_auth_url(state=state)
    except Exception as exc:
        log.exception("youtube_auth: failed to build auth URL")
        raise HTTPException(status_code=500, detail=str(exc))

    from fastapi.responses import RedirectResponse
    return RedirectResponse(auth_url)


@app.get("/api/youtube/callback")
async def youtube_callback(code: str = Query(None), state: str = Query(None), error: str = Query(None)):
    """Google OAuth callback — exchange code, store refresh token, redirect to /songs."""
    if error:
        log.warning("youtube_callback: Google returned error=%s", error)
        from fastapi.responses import RedirectResponse
        return RedirectResponse("/songs?youtube=error")

    if not code or not state:
        from fastapi.responses import RedirectResponse
        return RedirectResponse("/songs?youtube=error")

    user_id = _decode_yt_state(state)
    if not user_id:
        log.warning("youtube_callback: invalid or expired state token")
        from fastapi.responses import RedirectResponse
        return RedirectResponse("/songs?youtube=error")

    db_path = db.get_db_path()
    user = db.get_user_by_id(db_path, user_id)
    if not user:
        log.warning("youtube_callback: user %s not found", user_id)
        from fastapi.responses import RedirectResponse
        return RedirectResponse("/songs?youtube=error")

    redirect_uri = os.environ.get("YOUTUBE_REDIRECT_URI", "http://localhost:8080/api/youtube/callback")

    try:
        refresh_token = youtube_uploader.exchange_code(code=code, redirect_uri=redirect_uri, state=state)
    except Exception as exc:
        log.exception("youtube_callback: token exchange failed")
        from fastapi.responses import RedirectResponse
        return RedirectResponse("/songs?youtube=error")

    db.update_user(db_path, user_id, youtube_refresh_token=refresh_token)
    log.info("youtube_callback: stored refresh token for user %s", user_id)

    from fastapi.responses import RedirectResponse
    return RedirectResponse("/songs?youtube=connected")


class YouTubeUploadRequest(BaseModel):
    privacy: str = "unlisted"  # "public" | "unlisted" | "private"
    title: str | None = None


@app.post("/api/songs/variants/{variant_id}/upload-youtube")
async def upload_to_youtube(
    variant_id: int,
    body: YouTubeUploadRequest,
    current_user: dict = Depends(auth.get_current_user),
):
    """Upload a completed song variant to the user's YouTube channel."""
    is_admin = bool(current_user.get("is_admin", 0))
    plan = current_user.get("subscription_plan")
    if not is_admin and plan not in _YOUTUBE_PLANS:
        raise HTTPException(status_code=403, detail="YouTube upload requires Agency plan or above")

    if not current_user.get("youtube_refresh_token"):
        raise HTTPException(status_code=400, detail="YouTube not connected — visit /api/youtube/auth first")

    if body.privacy not in ("public", "unlisted", "private"):
        raise HTTPException(status_code=400, detail="privacy must be public, unlisted, or private")

    db_path = db.get_db_path()
    variant = db.get_song_variant_by_id(db_path, variant_id)
    if not variant or variant["user_id"] != current_user["id"]:
        raise HTTPException(status_code=404, detail="Song not found")
    if variant["status"] != "complete":
        raise HTTPException(status_code=400, detail="Song is not ready yet")

    title = body.title or db.get_lyric_title(db_path, variant["lyric_id"]) or f"Song #{variant_id}"

    # Prefer the D-ID avatar video (full motion) over the still-image mux when available.
    prebuilt_mp4 = None
    if variant.get("video_url"):
        prebuilt_mp4 = pathlib.Path("/data/videos") / f"{variant_id}.mp4"
        if not prebuilt_mp4.exists():
            prebuilt_mp4 = None  # file missing — fall back to FFmpeg mux

    try:
        youtube_url = youtube_uploader.upload_song_to_youtube(
            variant=variant,
            user=current_user,
            privacy=body.privacy,
            title=title,
            prebuilt_mp4=prebuilt_mp4,
        )
    except ValueError as exc:
        raise HTTPException(status_code=400, detail=str(exc))
    except subprocess.CalledProcessError as exc:
        log.error("upload_to_youtube: ffmpeg failed: %s", exc.stderr)
        raise HTTPException(status_code=500, detail="Audio processing failed")
    except Exception as exc:
        log.exception("upload_to_youtube: unexpected error")
        raise HTTPException(status_code=500, detail="Upload failed — please try again")

    db.update_song_variant(db_path, variant_id, youtube_url=youtube_url)
    return {"youtube_url": youtube_url}


# ── D-ID avatar lip-sync endpoints ───────────────────────────────────────────

_DID_PLANS = {"agency", "enterprise"}


@app.get("/api/did/avatars")
async def list_did_avatars(current_user: dict = Depends(auth.get_current_user)):
    """Return preset avatar list for the avatar picker modal."""
    is_admin = bool(current_user.get("is_admin", 0))
    plan = current_user.get("subscription_plan")
    if not is_admin and plan not in _DID_PLANS:
        raise HTTPException(status_code=403, detail="Avatar videos require Agency plan or above")
    return {"avatars": did_uploader.GENRE_AVATARS}


class CreateAvatarVideoRequest(BaseModel):
    source_url: str  # preset URL or /files/avatars/<filename>


@app.post("/api/songs/variants/{variant_id}/create-avatar-video")
async def create_avatar_video(
    variant_id: int,
    body: CreateAvatarVideoRequest,
    current_user: dict = Depends(auth.get_current_user),
):
    """Submit a D-ID lip-sync job for a completed song variant."""
    log.info("create_avatar_video: variant_id=%s user=%s body=%r",
             variant_id, current_user.get("id"), body.dict())

    is_admin = bool(current_user.get("is_admin", 0))
    plan = current_user.get("subscription_plan")
    if not is_admin and plan not in _DID_PLANS:
        raise HTTPException(status_code=403, detail="Avatar videos require Agency plan or above")

    if not did_uploader.did_enabled():
        raise HTTPException(status_code=503, detail="D-ID integration not configured (DID_API_KEY missing)")

    db_path = db.get_db_path()
    variant = db.get_song_variant_by_id(db_path, variant_id)
    if not variant or variant["user_id"] != current_user["id"]:
        raise HTTPException(status_code=404, detail="Song not found")
    if variant["status"] != "complete":
        raise HTTPException(status_code=400, detail="Song is not ready yet")
    if not variant.get("mp3_url"):
        raise HTTPException(status_code=400, detail="Song has no audio URL")

    backend_url = os.environ.get("BACKEND_URL", "").strip().rstrip("/")

    # Resolve relative avatar URLs to absolute so D-ID can fetch them
    source_url = body.source_url
    if source_url.startswith("/"):
        if not backend_url:
            raise HTTPException(
                status_code=503,
                detail="BACKEND_URL not configured — cannot resolve uploaded avatar URL",
            )
        source_url = backend_url + source_url

    webhook_url = f"{backend_url}/webhooks/did" if backend_url else None

    log.info("create_avatar_video: submitting to D-ID — source_url=%r audio_url=%r webhook=%r",
             source_url, variant["mp3_url"], webhook_url)

    try:
        job_id = did_uploader.submit_avatar_video(
            audio_url=variant["mp3_url"],
            source_url=source_url,
            webhook_url=webhook_url,
        )
    except ValueError as exc:
        log.error("create_avatar_video: D-ID rejected request for variant %s: %s", variant_id, exc)
        raise HTTPException(status_code=400, detail=str(exc))
    except Exception:
        log.exception("create_avatar_video: D-ID submission failed for variant %s", variant_id)
        raise HTTPException(status_code=500, detail="D-ID submission failed — try again")

    db.update_song_variant(db_path, variant_id, did_job_id=job_id)
    log.info("create_avatar_video: variant=%s job_id=%s", variant_id, job_id)
    return {"job_id": job_id, "status": "processing"}


@app.post("/api/avatars/upload")
async def upload_avatar_photo(
    file: UploadFile = File(...),
    current_user: dict = Depends(auth.get_current_user),
):
    """Upload a custom face photo to use as a D-ID avatar source."""
    is_admin = bool(current_user.get("is_admin", 0))
    plan = current_user.get("subscription_plan")
    if not is_admin and plan not in _DID_PLANS:
        raise HTTPException(status_code=403, detail="Avatar videos require Agency plan or above")

    content_type = file.content_type or ""
    if not content_type.startswith("image/"):
        raise HTTPException(status_code=400, detail="File must be an image (JPEG, PNG, WebP, etc.)")

    ext = pathlib.Path(file.filename or "photo.jpg").suffix.lower() or ".jpg"
    if ext not in (".jpg", ".jpeg", ".png", ".webp"):
        raise HTTPException(status_code=400, detail="Unsupported image format — use JPEG, PNG, or WebP")

    data = await file.read()
    if len(data) > 10 * 1024 * 1024:
        raise HTTPException(status_code=413, detail="Image must be under 10 MB")

    filename = f"{uuid.uuid4()}{ext}"
    dest = pathlib.Path("/data/avatars") / filename
    dest.write_bytes(data)
    log.info("upload_avatar_photo: saved %s (%d bytes) for user %s", filename, len(data), current_user["id"])
    return {"url": f"/files/avatars/{filename}", "filename": filename}


@app.post("/webhooks/did")
async def did_webhook(request: Request):
    """D-ID callback — fires when a talk job finishes. Downloads the MP4 and updates DB."""
    try:
        payload = await request.json()
    except Exception:
        raise HTTPException(status_code=400, detail="Invalid JSON body")

    job_id = payload.get("id")
    status = payload.get("status")
    result_url = payload.get("result_url")

    log.info("did_webhook: job_id=%s status=%s", job_id, status)

    if not job_id or status not in ("done", "error"):
        return {"ok": True}

    db_path = db.get_db_path()
    variant = db.get_song_variant_by_did_job_id(db_path, job_id)
    if not variant:
        log.warning("did_webhook: no variant found for job_id=%s", job_id)
        return {"ok": True}

    variant_id = variant["id"]

    if status == "error":
        log.error("did_webhook: D-ID job %s failed: %s", job_id, payload.get("error"))
        db.update_song_variant(db_path, variant_id, did_job_id=None)
        return {"ok": True}

    if not result_url:
        log.warning("did_webhook: done but no result_url for job %s", job_id)
        return {"ok": True}

    mp4_path = pathlib.Path("/data/videos") / f"{variant_id}.mp4"
    try:
        async with httpx.AsyncClient(timeout=120) as client:
            resp = await client.get(result_url)
            resp.raise_for_status()
            mp4_path.write_bytes(resp.content)
    except Exception:
        log.exception("did_webhook: failed to download MP4 for variant %s", variant_id)
        return {"ok": True}

    video_url = f"/files/videos/{variant_id}.mp4"
    db.update_song_variant(db_path, variant_id, video_url=video_url)
    log.info("did_webhook: variant=%s video stored at %s", variant_id, mp4_path)
    return {"ok": True}


@app.get("/api/songs/variants/{variant_id}/did-status")
async def did_status(
    variant_id: int,
    current_user: dict = Depends(auth.get_current_user),
):
    """Poll D-ID job status. Downloads the MP4 if done and not yet stored (webhook fallback)."""
    db_path = db.get_db_path()
    variant = db.get_song_variant_by_id(db_path, variant_id)
    if not variant or variant["user_id"] != current_user["id"]:
        raise HTTPException(status_code=404, detail="Song not found")

    if variant.get("video_url"):
        return {"status": "done", "video_url": variant["video_url"]}

    job_id = variant.get("did_job_id")
    if not job_id:
        return {"status": "none", "video_url": None}

    try:
        result = did_uploader.get_job_status(job_id)
    except Exception as exc:
        log.exception("did_status: get_job_status failed for variant %s", variant_id)
        raise HTTPException(status_code=500, detail=str(exc))

    if result["status"] == "done" and result.get("result_url"):
        mp4_path = pathlib.Path("/data/videos") / f"{variant_id}.mp4"
        if not mp4_path.exists():
            try:
                async with httpx.AsyncClient(timeout=120) as client:
                    resp = await client.get(result["result_url"])
                    resp.raise_for_status()
                    mp4_path.write_bytes(resp.content)
            except Exception:
                log.exception("did_status: download failed for variant %s", variant_id)
        if mp4_path.exists():
            video_url = f"/files/videos/{variant_id}.mp4"
            db.update_song_variant(db_path, variant_id, video_url=video_url)
            return {"status": "done", "video_url": video_url}

    return {"status": result["status"], "video_url": None}


# ── Scheduled Tasks ─────────────────────────────────────────────────────────

class ScheduledTaskParseRequest(BaseModel):
    natural_language: str = Field(min_length=1, max_length=500)


@app.post("/scheduled-tasks/parse")
async def parse_scheduled_task(
    body: ScheduledTaskParseRequest,
    current_user: dict = Depends(auth.get_current_user),
):
    """Parse a natural language schedule into a cron expression. No plan gate."""
    key = body.natural_language.lower().strip()
    if key in _parse_cache:
        return _parse_cache[key]

    client = get_anthropic_client()
    try:
        msg = client.messages.create(
            model="claude-haiku-4-5-20251001",
            max_tokens=128,
            system=(
                "You extract cron expressions from natural language schedule descriptions. "
                'Respond with ONLY a JSON object: {"cron_expression": "...", "schedule_label": "..."}\n'
                "- cron_expression: standard 5-field cron (minute hour day month weekday)\n"
                '- schedule_label: concise human-readable label, e.g. "Every Monday at 9am"\n'
                "If you cannot parse the input into a valid cron expression, respond with:\n"
                '{"error": "Could not parse schedule — try something like \'every Monday at 9am\'"}\n'
                "Do not include any other text."
            ),
            messages=[{"role": "user", "content": body.natural_language}],
        )
    except Exception:
        log.exception("parse_scheduled_task: Anthropic call failed")
        raise HTTPException(status_code=503, detail="Schedule parsing timed out — try again")

    try:
        result = json.loads(msg.content[0].text)
    except Exception:
        raise HTTPException(status_code=400, detail="Could not parse schedule — try again")

    if "error" in result:
        raise HTTPException(status_code=400, detail=result["error"])

    if len(_parse_cache) < 1024:
        _parse_cache[key] = result
    return result


@app.get("/scheduled-tasks")
async def list_scheduled_tasks(
    db_path: pathlib.Path = Depends(db.get_db_path_dep),
    current_user: dict = Depends(auth.get_current_user),
):
    if not _scheduled_task_plan_allowed(current_user):
        raise HTTPException(status_code=403, detail="Scheduled tasks require a Pro plan or above.")
    return db.get_scheduled_tasks_for_user(db_path, current_user["id"])


class ScheduledTaskCreateRequest(BaseModel):
    task_description: str = Field(min_length=1, max_length=2000)
    cron_expression: str = Field(min_length=1, max_length=100)
    schedule_label: str = Field(min_length=1, max_length=200)
    timezone: str = "UTC"


@app.post("/scheduled-tasks")
async def create_scheduled_task_endpoint(
    body: ScheduledTaskCreateRequest,
    db_path: pathlib.Path = Depends(db.get_db_path_dep),
    current_user: dict = Depends(auth.get_current_user),
):
    if not _scheduled_task_plan_allowed(current_user):
        raise HTTPException(status_code=403, detail="Scheduled tasks require a Pro plan or above.")

    limit = _scheduled_task_limit(current_user)
    if limit is not None:
        active_count = db.count_active_scheduled_tasks(db_path, current_user["id"])
        if active_count >= limit:
            plan = current_user.get("subscription_plan", "")
            raise HTTPException(
                status_code=403,
                detail=f"You've reached the limit of {limit} scheduled tasks on the {plan} plan. Upgrade to add more.",
            )

    # Validate cron expression — must be exactly 5 fields (APScheduler rejects 6-field)
    try:
        from croniter import croniter
        parts = body.cron_expression.strip().split()
        if len(parts) != 5 or not croniter.is_valid(body.cron_expression):
            raise ValueError("invalid")
    except ValueError:
        raise HTTPException(status_code=400, detail="Invalid cron expression")

    next_run = _scheduler_mod.compute_next_run(body.cron_expression)
    task = db.create_scheduled_task(
        db_path,
        user_id=current_user["id"],
        task_description=body.task_description,
        cron_expression=body.cron_expression,
        schedule_label=body.schedule_label,
        next_run=next_run,
        tz=body.timezone,
    )
    _scheduler_mod.add_job(task)
    return task


@app.delete("/scheduled-tasks/{task_id}")
async def delete_scheduled_task_endpoint(
    task_id: str,
    db_path: pathlib.Path = Depends(db.get_db_path_dep),
    current_user: dict = Depends(auth.get_current_user),
):
    if not _scheduled_task_plan_allowed(current_user):
        raise HTTPException(status_code=403, detail="Scheduled tasks require a Pro plan or above.")
    deleted = db.delete_scheduled_task(db_path, task_id, current_user["id"])
    if not deleted:
        raise HTTPException(status_code=404, detail="Task not found")
    _scheduler_mod.remove_job(task_id)
    return {"ok": True}


@app.patch("/scheduled-tasks/{task_id}/toggle")
async def toggle_scheduled_task(
    task_id: str,
    db_path: pathlib.Path = Depends(db.get_db_path_dep),
    current_user: dict = Depends(auth.get_current_user),
):
    if not _scheduled_task_plan_allowed(current_user):
        raise HTTPException(status_code=403, detail="Scheduled tasks require a Pro plan or above.")

    task = db.get_scheduled_task(db_path, task_id)
    if not task or task["user_id"] != current_user["id"]:
        raise HTTPException(status_code=404, detail="Task not found")

    new_active = 0 if task["is_active"] else 1

    if new_active == 1:
        # Re-activation limit check — prevents circumventing plan limits by deactivating+reactivating
        limit = _scheduled_task_limit(current_user)
        if limit is not None:
            active_count = db.count_active_scheduled_tasks(db_path, current_user["id"])
            if active_count >= limit:
                plan = current_user.get("subscription_plan", "")
                raise HTTPException(
                    status_code=403,
                    detail=f"You've reached the limit of {limit} scheduled tasks on the {plan} plan.",
                )

    if new_active == 1:
        next_run = _scheduler_mod.compute_next_run(task["cron_expression"])
        db.update_scheduled_task(db_path, task_id, is_active=1, next_run=next_run)
        _scheduler_mod.set_job_enabled(task_id, True)
    else:
        db.update_scheduled_task(db_path, task_id, is_active=0)
        _scheduler_mod.set_job_enabled(task_id, False)

    return db.get_scheduled_task(db_path, task_id)


# ── Websites endpoints ────────────────────────────────────────────────────────

@app.get("/websites")
async def list_websites(current_user: dict = Depends(auth.get_current_user)):
    db_path = db.get_db_path()
    sites = db.get_websites_for_user(db_path, current_user["id"])
    return [
        {k: v for k, v in s.items() if k != "files_json"}
        for s in sites
    ]


@app.post("/websites", status_code=201)
async def link_website(
    body: LinkWebsiteRequest,
    current_user: dict = Depends(auth.get_current_user),
):
    db_path = db.get_db_path()
    limit = _website_limit(current_user)
    if limit == 0:
        raise HTTPException(
            status_code=403,
            detail="Your plan does not include website management. Upgrade at zeusaidesign.com/pricing.",
        )
    if limit is not None:
        count = db.count_websites_for_user(db_path, current_user["id"])
        if count >= limit:
            raise HTTPException(
                status_code=403,
                detail=f"You've reached your plan limit of {limit} website{'s' if limit != 1 else ''}. Upgrade to add more.",
            )

    token = os.environ.get("NETLIFY_TOKEN", "").strip()
    if not token:
        raise HTTPException(status_code=503, detail="Netlify integration not configured.")

    try:
        import netlify_manager
        site_info = netlify_manager.resolve_site_name(body.netlify_site_name, token)
    except RuntimeError as exc:
        raise HTTPException(status_code=404, detail=str(exc))

    existing = db.get_website_by_netlify_id(db_path, site_info["id"], current_user["id"])
    if existing:
        raise HTTPException(status_code=409, detail="This Netlify site is already linked to your account.")

    site = db.create_website(
        db_path,
        user_id=current_user["id"],
        netlify_site_id=site_info["id"],
        netlify_site_name=site_info["name"],
        site_url=site_info["ssl_url"],
        client_name=body.client_name,
        files_json=None,
    )
    return {k: v for k, v in site.items() if k != "files_json"}


@app.put("/websites/{website_id}")
async def update_website_record(
    website_id: str,
    body: UpdateWebsiteRequest,
    current_user: dict = Depends(auth.get_current_user),
):
    db_path = db.get_db_path()
    site = db.get_website_by_id(db_path, website_id, current_user["id"])
    if not site:
        raise HTTPException(status_code=404, detail="Website not found.")

    updates: dict = {}
    if body.client_name is not None:
        updates["client_name"] = body.client_name

    if body.sync_files:
        token = os.environ.get("NETLIFY_TOKEN", "").strip()
        if not token:
            raise HTTPException(status_code=503, detail="Netlify integration not configured.")
        try:
            import netlify_manager, json as _json
            files = netlify_manager.fetch_site_files(site["netlify_site_id"], token)
            updates["files_json"] = _json.dumps(files)
        except RuntimeError as exc:
            raise HTTPException(status_code=502, detail=f"Netlify fetch failed: {exc}")

    if updates:
        db.update_website(db_path, website_id, **updates)

    updated = db.get_website_by_id(db_path, website_id, current_user["id"])
    return {k: v for k, v in updated.items() if k != "files_json"}


@app.delete("/websites/{website_id}", status_code=204)
async def unlink_website(
    website_id: str,
    current_user: dict = Depends(auth.get_current_user),
):
    db_path = db.get_db_path()
    deleted = db.delete_website(db_path, website_id, current_user["id"])
    if not deleted:
        raise HTTPException(status_code=404, detail="Website not found.")
    return Response(status_code=204)


# ── Tasks endpoints ───────────────────────────────────────────────────────────

@app.get("/tasks")
async def get_tasks(current_user: dict = Depends(auth.get_current_user)):
    is_admin = bool(current_user.get("is_admin", 0))
    plan = current_user.get("subscription_plan")
    status = current_user.get("subscription_status", "free")
    if not (is_admin or (status == "active" and plan == "enterprise")):
        raise HTTPException(status_code=403, detail="Enterprise plan required")
    db_path = db.get_db_path()
    # Ensure tasks table exists (handles DBs initialised before this feature was added)
    db.init_user_tables(db_path)
    try:
        return db.get_tasks_for_user(db_path, current_user["id"])
    except Exception:
        log.exception("get_tasks: DB error for user %s", current_user["id"])
        return []


@app.delete("/tasks/{task_id}")
async def delete_task(task_id: str, current_user: dict = Depends(auth.get_current_user)):
    is_admin = bool(current_user.get("is_admin", 0))
    plan = current_user.get("subscription_plan")
    status = current_user.get("subscription_status", "free")
    if not (is_admin or (status == "active" and plan == "enterprise")):
        raise HTTPException(status_code=403, detail="Enterprise plan required")
    db_path = db.get_db_path()
    deleted = db.delete_task(db_path, task_id, current_user["id"])
    if not deleted:
        raise HTTPException(status_code=404, detail="Task not found")
    return {"ok": True}


# ── Existing REST endpoints ───────────────────────────────────────────────────

@app.get("/sessions")
async def get_sessions(current_user: dict = Depends(auth.get_current_user)):
    if history is None:
        return []
    return history.list_sessions_for_user(current_user["id"])


@app.get("/history/{session_id}")
async def get_history(session_id: str, current_user: dict = Depends(auth.get_current_user)):
    if history is None:
        raise HTTPException(status_code=503, detail="Server still initialising")
    transcript = history.get_transcript_if_owner(session_id, current_user["id"])
    if transcript is None:
        raise HTTPException(status_code=404, detail="Session not found")
    return transcript


@app.get("/tunnel-url")
async def tunnel_url_endpoint():
    return {"url": get_tunnel_url()}


@app.post("/export")
async def export_document(body: ExportRequest):
    if body.format == "pdf":
        file_bytes = generate_pdf(body.text, body.title)
        media_type = "application/pdf"
        filename = f"{slugify(body.title)}.pdf"
    elif body.format == "docx":
        file_bytes = generate_docx(body.text, body.title)
        media_type = "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
        filename = f"{slugify(body.title)}.docx"
    else:
        raise HTTPException(status_code=400, detail="format must be pdf or docx")
    return Response(
        content=file_bytes,
        media_type=media_type,
        headers={"Content-Disposition": f'attachment; filename="{filename}"'},
    )


@app.get("/download/{filename}")
async def download_file(filename: str):
    import tempfile
    _railway = bool(os.environ.get("RAILWAY_ENVIRONMENT") or os.environ.get("RAILWAY_PROJECT_ID"))
    downloads_dir = pathlib.Path("/data/downloads" if _railway else tempfile.gettempdir()) / "zeus_downloads"
    file_path = downloads_dir / filename
    # Prevent path traversal
    if not file_path.resolve().is_relative_to(downloads_dir.resolve()):
        raise HTTPException(status_code=400, detail="Invalid filename")
    if not file_path.exists():
        raise HTTPException(status_code=404, detail="File not found or expired")
    display_name = filename.split("_", 1)[-1] if "_" in filename else filename
    return Response(
        content=file_path.read_bytes(),
        media_type="application/zip",
        headers={
            "Content-Disposition": f'attachment; filename="{display_name}"',
            "Content-Length": str(file_path.stat().st_size),
        },
    )


@app.get("/sitemap.xml", include_in_schema=False)
async def sitemap():
    path = pathlib.Path(__file__).parent / "sitemap.xml"
    return Response(content=path.read_text(encoding="utf-8"), media_type="application/xml")


@app.get("/health")
async def health():
    log.info("GET /health — ok")
    return {"status": "ok"}


@app.get("/ad-poster", include_in_schema=False)
async def ad_poster():
    html = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Zeus AI Design</title>
<style>
  * { margin: 0; padding: 0; box-sizing: border-box; }

  body {
    width: 1200px;
    height: 630px;
    overflow: hidden;
    background: #000;
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
    display: flex;
    align-items: center;
    justify-content: center;
  }

  .card {
    width: 1200px;
    height: 630px;
    background: #000;
    position: relative;
    display: flex;
    flex-direction: column;
    align-items: flex-start;
    justify-content: center;
    padding: 80px 100px;
    overflow: hidden;
  }

  /* Grid overlay */
  .card::before {
    content: '';
    position: absolute;
    inset: 0;
    background-image:
      linear-gradient(rgba(0, 255, 65, 0.04) 1px, transparent 1px),
      linear-gradient(90deg, rgba(0, 255, 65, 0.04) 1px, transparent 1px);
    background-size: 60px 60px;
    pointer-events: none;
  }

  /* Glow bloom */
  .card::after {
    content: '';
    position: absolute;
    top: -200px;
    right: -200px;
    width: 700px;
    height: 700px;
    background: radial-gradient(circle, rgba(0, 255, 65, 0.12) 0%, transparent 70%);
    pointer-events: none;
  }

  .bolt {
    font-size: 72px;
    line-height: 1;
    margin-bottom: 24px;
    filter: drop-shadow(0 0 24px #00ff41);
  }

  .headline {
    font-size: 80px;
    font-weight: 800;
    color: #00ff41;
    letter-spacing: -2px;
    line-height: 1;
    text-shadow: 0 0 40px rgba(0, 255, 65, 0.5);
    margin-bottom: 8px;
  }

  .sub {
    font-size: 80px;
    font-weight: 800;
    color: #fff;
    letter-spacing: -2px;
    line-height: 1;
    margin-bottom: 32px;
  }

  .tagline {
    font-size: 26px;
    font-weight: 400;
    color: rgba(255, 255, 255, 0.55);
    letter-spacing: 0.5px;
    margin-bottom: 48px;
  }

  .url {
    font-size: 22px;
    font-weight: 600;
    color: #00ff41;
    letter-spacing: 1px;
    border: 1.5px solid rgba(0, 255, 65, 0.4);
    padding: 10px 24px;
    border-radius: 4px;
    text-transform: lowercase;
  }

  /* Corner accent lines */
  .corner {
    position: absolute;
    width: 40px;
    height: 40px;
    border-color: rgba(0, 255, 65, 0.3);
    border-style: solid;
  }
  .corner-tl { top: 32px; left: 32px; border-width: 2px 0 0 2px; }
  .corner-tr { top: 32px; right: 32px; border-width: 2px 2px 0 0; }
  .corner-bl { bottom: 32px; left: 32px; border-width: 0 0 2px 2px; }
  .corner-br { bottom: 32px; right: 32px; border-width: 0 2px 2px 0; }
</style>
</head>
<body>
  <div class="card">
    <div class="corner corner-tl"></div>
    <div class="corner corner-tr"></div>
    <div class="corner corner-bl"></div>
    <div class="corner corner-br"></div>

    <div class="bolt">⚡</div>
    <div class="headline">Zeus AI</div>
    <div class="sub">Design.</div>
    <div class="tagline">Websites · Writing · Research · Business — powered by AI</div>
    <div class="url">zeusaidesign.com</div>
  </div>
</body>
</html>"""
    return HTMLResponse(content=html)


# Serve downloaded song MP3s from the Railway volume.
# MUST be mounted before the SPA catch-all below — order matters in FastAPI routing.
from fastapi.staticfiles import StaticFiles as _StaticFiles
_song_storage = pathlib.Path(os.environ.get("SONG_STORAGE_PATH", "/data/songs"))
_song_storage.mkdir(parents=True, exist_ok=True)
app.mount("/files/songs", _StaticFiles(directory=str(_song_storage)), name="songs")

_avatar_storage = pathlib.Path("/data/avatars")
_avatar_storage.mkdir(parents=True, exist_ok=True)
app.mount("/files/avatars", _StaticFiles(directory=str(_avatar_storage)), name="avatars")

_video_storage = pathlib.Path("/data/videos")
_video_storage.mkdir(parents=True, exist_ok=True)
app.mount("/files/videos", _StaticFiles(directory=str(_video_storage)), name="videos")

# Serve built React app from web/dist/
# Mount /assets for Vite bundles, then a catch-all that returns index.html for
# any unmatched path so client-side routes (e.g. /tasks, /billing) survive refresh.
_dist = pathlib.Path(__file__).parent.parent / "web" / "dist"
if _dist.exists():
    from fastapi.staticfiles import StaticFiles
    from fastapi.responses import FileResponse

    _assets_dir = _dist / "assets"
    if _assets_dir.exists():
        app.mount("/assets", StaticFiles(directory=str(_assets_dir)), name="assets")

    @app.get("/{full_path:path}", include_in_schema=False)
    async def serve_spa(full_path: str):
        # Serve real files that live in dist root (favicon.ico, robots.txt, etc.)
        candidate = _dist / full_path
        if candidate.exists() and candidate.is_file():
            return FileResponse(str(candidate))
        # Fall back to index.html for all client-side routes
        return FileResponse(str(_dist / "index.html"))


if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000, reload=False)
