GENRE_PRESETS = {
    "country":  "country ballad, acoustic guitar, slide guitar, warm storytelling vocals, moderate tempo",
    "reggae":   "reggae, off-beat skank guitar, dub bass, laid-back vocals, 80 BPM",
    "pop":      "modern pop, polished production, catchy synth melody, clear vocals, 120 BPM",
    "rock":     "rock anthem, electric guitar, driving drums, powerful vocals, 130 BPM",
    "hiphop":   "hip-hop, 808 bass, trap hi-hats, rhythmic vocal delivery, 90 BPM",
    "lofi":     "lo-fi hip-hop, dusty piano, vinyl crackle, mellow vocals, 75 BPM",
    "edm":      "EDM, four-on-the-floor kick, big synth lead, energetic vocals, 128 BPM",
    "acoustic": "acoustic singer-songwriter, fingerpicked guitar, intimate vocals, 90 BPM",
    "irishjig":  "Irish jig, fiddle, tin whistle, accordion, fast tempo, 160 BPM, energetic traditional Irish dance music",
    "irishfolk": "Irish folk song, acoustic guitar, fiddle, storytelling vocals, slow to moderate tempo, traditional Celtic feel",
    "blues":     "blues, electric guitar, soulful vocals, slow to mid tempo, 12-bar blues progression",
    "soul":      "soul music, warm brass, gospel-influenced vocals, rhythm section, emotional delivery",
    "rnb":        "R&B, smooth production, silky vocals, bass-forward, contemporary feel, 90 BPM",
    "bluessoul":  "blues soul fusion, soulful vocals, warm guitar, gospel undertones, emotional delivery, slow to mid tempo",
    "drumandbass": "drum and bass, heavy rolling bassline, fast breakbeats, 170 BPM, electronic production, UK rave energy",
    "grime":       "grime, aggressive 140 BPM beat, dark synth stabs, UK drill influence, fast paced MCing, East London sound",
    "ukgarage":    "UK garage, 2-step rhythm, pitched vocals, 130 BPM, shuffled hi-hats, bouncy bassline, late 90s London underground sound",
    "jungle":      "jungle music, Amen breakbeat, reggae samples, ragga vocals, sub bass, 160 BPM, early 90s UK rave sound, dark atmospheric",
    "bassline":    "bassline house, heavy 4x4 kick, wobbling sub bassline, pitched male vocals, 130 BPM, Sheffield underground sound, raw club energy",
    "house":       "house music, 4x4 kick drum, soulful vocals, deep bassline, 126 BPM, Chicago roots, uplifting club energy, classic house piano",
    "loversrock":  "lovers rock, romantic reggae, smooth bassline, sweet soulful vocals, 70s Caribbean warmth, slow sensual rhythm",
    "ukdrill":     "UK drill, dark 808 bassline, sliding minor melodies, aggressive flow, 140 BPM, South London sound, trap hi-hats",
    "kpop":        "K-pop, polished production, catchy hook, bright synth melody, precise rhythm, 120 BPM, Korean pop aesthetic, energetic and clean",
}
