INSTRUMENTAL_SUFFIX = "fully instrumental, extended arrangement, prominent deep bass, dynamic structure with build ups and breakdowns, musical complexity, clever chord progressions, layered instrumentation, extended intro and outro, detailed production, rich harmonic content, bass-forward mix, evolving arrangement that develops throughout, professional instrumental composition"

GENRE_PRESETS = {
    "country":  "country ballad, acoustic guitar, slide guitar, warm storytelling vocals, moderate tempo",
    "reggae":   "reggae, off-beat skank guitar, dub bass, laid-back vocals, 80 BPM",
    "pop":      "modern pop, polished production, catchy synth melody, clear vocals, 120 BPM",
    "rock":     "rock anthem, electric guitar, driving drums, powerful vocals, 130 BPM",
    "hiphop":   "hip-hop, 808 bass, trap hi-hats, rhythmic vocal delivery, 90 BPM",
    "lofi":     "lo-fi hip-hop, dusty piano, vinyl crackle, mellow vocals, 75 BPM",
    "edm":      "EDM, four-on-the-floor kick, big synth lead, energetic vocals, 128 BPM",
    "acoustic": "acoustic singer-songwriter, fingerpicked guitar, intimate vocals, 90 BPM",
    "irishjig":  "Irish jig, fiddle, tin whistle, accordion, fast tempo, 160 BPM, energetic traditional Irish dance music",
    "irishfolk": "Irish folk song, acoustic guitar, fiddle, storytelling vocals, slow to moderate tempo, traditional Celtic feel",
    "blues":     "blues, electric guitar, soulful vocals, slow to mid tempo, 12-bar blues progression",
    "soul":      "soul music, warm brass, gospel-influenced vocals, rhythm section, emotional delivery",
    "rnb":        "R&B, smooth production, silky vocals, bass-forward, contemporary feel, 90 BPM",
    "bluessoul":  "blues soul fusion, soulful vocals, warm guitar, gospel undertones, emotional delivery, slow to mid tempo",
    "drumandbass": "drum and bass, heavy rolling bassline, fast breakbeats, 170 BPM, electronic production, UK rave energy",
    "grime":       "grime, aggressive 140 BPM beat, dark synth stabs, UK drill influence, fast paced MCing, East London sound",
    "ukgarage":    "UK garage, 2-step rhythm, pitched vocals, 130 BPM, shuffled hi-hats, bouncy bassline, late 90s London underground sound",
    "jungle":      "jungle music, Amen breakbeat, reggae samples, ragga vocals, sub bass, 160 BPM, early 90s UK rave sound, dark atmospheric",
    "bassline":    "bassline house, heavy 4x4 kick, wobbling sub bassline, pitched male vocals, 130 BPM, Sheffield underground sound, raw club energy",
    "house":       "house music, 4x4 kick drum, soulful vocals, deep bassline, 126 BPM, Chicago roots, uplifting club energy, classic house piano",
    "loversrock":  "lovers rock, romantic reggae, smooth bassline, sweet soulful vocals, 70s Caribbean warmth, slow sensual rhythm",
    "ukdrill":     "UK drill, dark 808 bassline, sliding minor melodies, aggressive flow, 140 BPM, South London sound, trap hi-hats",
    "kpop":        "K-pop, polished production, catchy hook, bright synth melody, precise rhythm, 120 BPM, Korean pop aesthetic, energetic and clean",
    "deepsoulblues": "deep soul blues, raw emotional vocals, slow burning guitar, gospel undertones, heavy heartfelt delivery, southern blues roots, 60-75 BPM",
    "niche":          "niche music, Sheffield bassline, fast bouncy 4x4 kick drum, pitched female vocals, speed garage influence, 138 BPM, Yorkshire club energy, wobbling sub bass, T2 Heartbroken style",
    "ukstreetsoul":   "UK street soul, smooth soulful vocals, warm RnB production, urban British feel, laid back groove, 90 BPM",
    "classical":      "classical orchestral, strings, piano, full orchestra, dynamic composition, cinematic arrangement",
    "indie":          "indie rock, jangly guitars, introspective lyrics, lo-fi warmth, alternative sound, 110 BPM",
    "techno":         "techno, driving 4x4 kick, dark hypnotic synths, 138 BPM, industrial atmosphere, Berlin underground sound",
    "technhouse":     "tech house, groovy bassline, minimal percussion, 125 BPM, underground club energy, hypnotic loop",
    "hyperpop":       "hyperpop, heavily distorted 808s, pitched up vocals, chaotic production, glitchy effects, 150 BPM, internet age sound",
    "afrobeats":      "afrobeats, infectious percussion, talking drum, warm bass, joyful vocal melody, West African rhythm, 100 BPM",
    "amapiano":       "amapiano, log drum bassline, jazzy piano chords, South African house rhythm, 112 BPM, smooth and deep",
    "driftphonk":     "drift phonk, aggressive 808 bass, cowbell percussion, dark Memphis rap influence, high energy drift culture, 140 BPM",
    "jerseyclub":     "Jersey Club, chopped vocal samples, rapid hi-hat patterns, 140 BPM, Newark NJ club sound, energetic dance floor energy",
    "afroswing":      "afroswing, smooth UK R&B vocals, gentle afrobeats percussion underneath, melodic guitar, 90 BPM, romantic intimate feel, British urban sound, J Hus style, laid back swing rhythm, NOT heavy afrobeats drums",
    "rastadub":       "rasta dub, heavy echo and reverb, deep rolling bassline, roots reggae rhythm, spiritual Rastafarian lyrics, slow burning groove, 70 BPM, Jamaican sound system culture, conscious message",
    "deeprotbassline": "UK bassline, heavy 4x4 kick drum, deep rolling sub bass, 138 BPM, Nottingham bassline sound, UK garage influence, chopped female vocals, euphoric rave energy, modern bass music",
    "jazz":            "jazz, smooth improvised saxophone, upright bass walking lines, brushed drums, jazz piano chords, bebop influence, warm intimate club sound, 120 BPM swing",
}
