KIDS_STORY_PRESETS = {
    "pop":       "gentle upbeat children's background instrumental, bright piano and bells, soft warm percussion, playful whimsical melody, no vocals, 90 BPM",
    "classical": "gentle orchestral children's background instrumental, soft strings and warm woodwinds, tender and whimsical, cinematic storytelling feel, no vocals",
    "acoustic":  "gentle fingerpicked acoustic guitar instrumental, warm and intimate, soft and peaceful, children's story background music, no vocals",
    "reggae":    "gentle reggae background instrumental, light laid-back rhythm, warm bass and guitar, soft tropical feel, children's background music, no vocals",
}

INSTRUMENTAL_SUFFIX = "fully instrumental, extended arrangement, prominent deep bass, dynamic structure with build ups and breakdowns, musical complexity, clever chord progressions, layered instrumentation, extended intro and outro, detailed production, rich harmonic content, bass-forward mix, evolving arrangement that develops throughout, professional instrumental composition"

GENRE_PRESETS = {
    "country":  "country ballad, acoustic guitar, slide guitar, pedal steel, warm storytelling vocals, dynamic verse-chorus structure, moderate tempo",
    "reggae":   "reggae, off-beat rhythm guitar upstroke, dub bass, warm organ fill, laid-back vocals, 80 BPM, roots feel",
    "pop":      "modern pop, polished layered production, catchy synth melody, anthemic chorus, stacked harmonies, bright clear vocals, 120 BPM",
    "rock":     "rock anthem, electric guitar riff, driving live drums, powerful vocals, dynamic build to chorus, 130 BPM",
    "hiphop":   "hip-hop, boom bap drums, sampled soul loop, 808 bass, punchy snare crack, rhythmic lyrical flow, 90 BPM, urban storytelling",
    "lofi":     "lo-fi hip-hop, dusty chopped sample, vinyl crackle, warm tape saturation, mellow laid-back vocals, 75 BPM",
    "edm":      "EDM, four-on-the-floor kick, supersawing lead synth, massive drop, energetic vocals, sidechain pump, 128 BPM",
    "acoustic": "acoustic singer-songwriter, fingerpicked guitar, intimate close-mic vocals, subtle room ambience, 90 BPM",
    "irishjig":  "Irish jig, fiddle, tin whistle, accordion, fast tempo, 160 BPM, energetic traditional Irish dance music",
    "irishfolk": "Irish folk song, acoustic guitar, fiddle, heartfelt storytelling vocals, slow to moderate tempo, traditional Celtic feel",
    "blues":     "blues, electric guitar with expressive bends, warm amp tone, soulful vocals, slow to mid tempo, 12-bar blues progression",
    "soul":      "soul music, warm brass section, Hammond organ, gospel-influenced layered vocals, deep rhythm section, emotional heartfelt delivery, 85 BPM",
    "rnb":        "R&B, smooth lush production, silky vocal harmonies, warm synth pads, bass-forward, contemporary feel, 90 BPM",
    "bluessoul":  "blues soul fusion, soulful vocals, warm guitar, gospel undertones, Hammond organ, emotional delivery, slow to mid tempo",
    "drumandbass": "drum and bass, rolling Reese bass, chopped amen break, fast rolling drums, 170 BPM, electronic production, UK rave energy, sub bass pressure",
    "grime":       "grime, 140 BPM icy beat, cold minimal synth stabs, hard snare hits, rapid MC delivery, East London sound, aggressive dark energy",
    "ukgarage":    "UK garage, 2-step rhythm, pitched vocals, 130 BPM, shuffled hi-hats, bouncy bassline, skittering percussion, late 90s London underground sound",
    "jungle":      "jungle music, sliced Amen breakbeat, reggae samples, ragga vocals, heavy sub bass, 160 BPM, early 90s UK rave sound, dub echo, dark atmospheric",
    "bassline":    "bassline house, heavy 4x4 kick, warped wobbling sub bassline, pitched male vocals, organ stab, 130 BPM, Sheffield underground sound, raw club energy",
    "house":       "house music, 4x4 kick drum, warm organ fills, lush chord stabs, soulful vocals, deep bassline, 126 BPM, Chicago roots, uplifting club energy, classic house piano",
    "loversrock":  "lovers rock, romantic reggae, smooth bassline, warm guitar, sweet soulful vocals, lush harmonies, 70s Caribbean warmth, slow sensual rhythm",
    "ukdrill":     "UK drill, dark rolling 808 bassline, sliding chromatic minor melodies, aggressive flow, 140 BPM, South London sound, trap hi-hats, ominous atmosphere",
    "kpop":        "K-pop, polished production, catchy hook, bright synth melody, precise rhythm, 120 BPM, Korean pop aesthetic, energetic and clean",
    "deepsoulblues": "deep soul blues, raw emotional vocals, slow burning guitar, gospel undertones, heavy heartfelt delivery, southern blues roots, 60-75 BPM",
    "niche":          "niche music, UK bassline, fast bouncy 4x4 kick drum, pitched female vocals, speed garage influence, 138 BPM, Northern underground club energy, wobbling sub bass, speed garage hookline feel",
    "ukstreetsoul":   "UK street soul, smooth soulful vocals, warm RnB production, urban British feel, laid back groove, 90 BPM",
    "classical":      "classical orchestral, strings, piano, full orchestra, dynamic composition, cinematic arrangement",
    "indie":          "indie rock, jangly guitars, introspective lyrics, lo-fi warmth, alternative sound, 110 BPM",
    "techno":         "techno, driving 4x4 kick, dark hypnotic synths, 138 BPM, industrial atmosphere, Berlin underground sound",
    "technhouse":     "tech house, groovy bassline, minimal percussion, 125 BPM, underground club energy, hypnotic loop",
    "hyperpop":       "hyperpop, heavily distorted 808s, pitched up vocals, chaotic production, glitchy effects, 150 BPM, internet age sound",
    "afrobeats":      "afrobeats, infectious percussion, talking drum, warm bass, joyful vocal melody, West African rhythm, 100 BPM",
    "amapiano":       "amapiano, log drum bassline, jazzy piano chords, South African house rhythm, 112 BPM, smooth and deep",
    "driftphonk":     "drift phonk, aggressive 808 bass, cowbell percussion, dark Memphis rap influence, high energy drift culture, 140 BPM",
    "jerseyclub":     "Jersey Club, chopped vocal samples, rapid hi-hat patterns, 140 BPM, Newark NJ club sound, energetic dance floor energy",
    "afroswing":      "afroswing, smooth UK R&B vocals, gentle afrobeats percussion underneath, melodic guitar, 90 BPM, romantic intimate feel, British urban sound, melodic British Afro-pop vibe, laid back swing rhythm, NOT heavy afrobeats drums",
    "rastadub":       "rasta dub, heavy echo and reverb, deep rolling bassline, roots reggae rhythm, spiritual Rastafarian lyrics, slow burning groove, 70 BPM, Jamaican sound system culture, conscious message",
    "deeprotbassline": "UK bassline, heavy 4x4 kick drum, deep rolling sub bass, 138 BPM, Nottingham bassline sound, UK garage influence, chopped female vocals, euphoric rave energy, modern bass music",
    "purebassline":    "UK bassline, 4x4 four to the floor beat, heavy warped modulated sub bass with LFO wobble, organ stabs, pitched-up female R&B vocal chops, 140 BPM, bouncy energetic dancefloor energy, shuffled house drums, speed garage influence, hard hitting pumping bassline, euphoric Northern rave energy",
    "jazz":            "jazz, smooth improvised saxophone, upright bass walking lines, brushed drums, jazz piano chords, bebop influence, warm intimate club sound, 120 BPM swing",
    "swing":           "swing jazz, big band, upbeat swing rhythm, brass section, walking bassline, 1940s swing era, lively horns, swing drums with brushes, danceable swing groove, vintage big band sound, energetic jazz orchestra",
    "vocaljazz":       "vocal jazz, smooth jazz vocals, intimate crooning, piano and upright bass, brushed drums, sophisticated jazz harmony, lounge jazz atmosphere, warm emotional delivery, classic jazz standards feel, velvet smooth singing, late night jazz club mood",
    "electronicfunk":  "electronic funk, talk box vocoder vocals, smooth slow funk groove, electronic synthesizer bassline, French electronic funk production style, 95 BPM, soulful R&B feeling, warm analogue synths, silky smooth production, 80s electro funk, vocoder robot voice effect, late night smooth groove",
    "syntheticpop":    "synthetic pop, bright catchy synthesizers, four on the floor beat, polished production, euphoric pop hooks, 128 BPM, 80s synth pop influence, glossy electronic sound, irresistible chorus",
    "ragga":           "ragga dancehall, digital riddim, Jamaican vocals, patois delivery, bashment energy, 90 BPM, dancehall beat, Caribbean flow",
    "dubstep":         "dubstep, massive wobble bass, half time drum pattern, 140 BPM, dark electronic atmosphere, bass drop, heavy sub bass, UK dubstep sound, cinematic tension building, heavy UK dubstep production",
    "bhangra":         "bhangra, dhol drum, tumbi, energetic Punjabi vocals, traditional Indian folk meets modern beat, 140 BPM, wedding celebration energy, Punjabi lyrics, bhangra dance rhythm",
    "rockney":         "cockney pub rock, honky tonk piano, acoustic strumming guitar, singalong chorus, working class London storytelling, cheerful upbeat tempo, 130 BPM, East End London culture, knees up dance rhythm, traditional British pub band sound, singalong crowd vocals, jovial cockney delivery, music hall influenced, pearly kings and queens energy",
    "metal":           "heavy metal, distorted electric guitar, double kick drum, powerful screaming vocals, 160 BPM, dark aggressive atmosphere, guitar solo, massive wall of sound, classic heavy metal production, thunderous guitar riffs",
    "reggaeton":       "reggaeton, dembow rhythm, 95 BPM, urban Latin beat, heavy 808 bass, perreo energy, Spanish lyrics, reggaeton flow, Caribbean Latin fusion, infectious Latin urban energy, perreo production style, trap infused Latin production",
    "latintrap":       "Latin trap, dark 808 bass, trap hi-hats, Spanish rap flow, 140 BPM, moody atmospheric production, Latin street sound, melodic Spanish vocals, dark trap beats, dark melodic Spanish rap, moody urban Latin production, urban Latin darkness",
    "rootsreggae":    "roots reggae, heavy one drop drum pattern, deep rolling bass, classic reggae offbeat rhythm guitar upstroke, 75 BPM, conscious spiritual lyrics, vintage Studio One sound, warm analogue production, Jamaican roots sound, soulful reggae vocals, organic live band feel",
    "countryamericana": "country Americana, outlaw country storytelling, acoustic guitar and banjo, hip-hop rhythms underneath, working class narratives, heartfelt vocals, 95 BPM, Southern US production, trap influenced country beat, soulful Americana feel, genre blending country and urban, raw authentic delivery",
    "southemsoul":      "Southern soul, warm deep Alabama or Mississippi soul, gospel influenced vocals, Hammond organ, horns section, deep groove rhythm section, 75 BPM, Muscle Shoals sound, raw emotional delivery, soulful storytelling, Southern church feel, classic deep Southern soul production, raw emotional gospel delivery, warm analogue recording",
    "traditionalpop":   "traditional pop, classic crooner style, orchestral arrangement, lush strings, smooth romantic vocals, 1950s 1960s pop, timeless melody, sophisticated easy listening, big band pop, warm nostalgic sound, elegant orchestration",
    "rocknroll":        "rock and roll, 1950s rock n roll, driving backbeat, electric guitar riffs, upright bass slap, energetic piano, rockabilly energy, danceable rebellious rhythm, vintage rock and roll sound, jukebox classic feel",
    "trap":             "trap, heavy 808 bass, rapid hi-hat rolls, dark atmospheric production, sliding minor melodies, 140 BPM, Atlanta trap sound, dark melodic trap, distorted 808 sub bass, hard hitting snare claps, slow grinding beat, triplet hi-hats",
    "eastcoasthiphop":  "East Coast hip-hop, boom bap drums, jazz sample flip, heavy snare, lyrical wordplay, 90 BPM, classic New York underground sound, soulful jazz sampling, punchy kick and snare, smooth piano loops, authentic street storytelling",
    "poprap":           "pop rap, catchy melodic hooks over trap production, smooth crossover flow, upbeat polished sound, 110 BPM, commercial hip-hop, infectious singalong chorus, melodic verses, vibrant pop energy, radio-ready production, feel-good urban pop",
    "synthwave":        "synthwave, retro 80s synthesizers, pulsing arpeggiated synth, neon atmospheric pads, drum machine beat, 120 BPM, nostalgic electronic sound, cinematic synth layers, retrofuturist aesthetic, driving bass synth, glowing retro production",
    "gospel":           "gospel, powerful choir harmonies, Hammond organ, uplifting spiritual energy, hand claps, soulful delivery, 90 BPM, church-inspired production, call and response, gospel harmonies, stirring emotional delivery, testifying vocals",
    "trapsoul":         "trap soul, dark atmospheric R&B, melodic vocals over trap production, slow sensual groove, emotional delivery, 70 BPM, moody production, deep 808 bass, lush synth pads, contemporary R&B meets trap, introspective heartfelt lyrics",
    "meditation":       "meditation music, calming ambient synthesizers, singing bowls, gentle nature sounds, peaceful drone pads, slow 60 BPM, healing frequencies, gentle flute, serene soundscape, soft layered tones, tranquil breathing space, no percussion",
    "christmas":        "upbeat festive Christmas music, cheerful jingle bells, warm major key melody, joyful holiday spirit, bright happy orchestration, classic Christmas carol feel, merry uplifting tempo, warm sleigh bells, family Christmas warmth, positive festive energy, NOT dark or melancholic",
    "corridos":          "corridos, Mexican folk storytelling, acoustic guitar and bajo sexto, horn section, polka-influenced norteño rhythm, 130 BPM, authentic regional Mexican sound, heartfelt vocal delivery, traditional corrido narrative structure, vibrant brass, accordion, sincere passionate performance",
    "healingfrequency":  "healing frequency music, 432 Hz tuning, solfeggio frequencies, deep meditative tones, calming ambient pads, singing bowls, gentle drone, sound bath atmosphere, peaceful healing vibrations, no vocals, deeply relaxing wellness music, spa and meditation sound therapy",
}
