import portrait from '../assets/memorial/heavenly-portrait.webp';
import landscape from '../assets/memorial/heavenly-landscape.webp';

/**
 * "Heavenly" memorial-page background (2026-09-30): a glowing stairway rising
 * through clouds into warm golden light, with blossom branches at the edges.
 *
 * The artwork is original and procedurally generated by
 * web-beats/scripts/generate_heavenly_bg.py (noise-based clouds, rays, a
 * perspective stairway) — no photo, stock image or third-party asset, so
 * there is nothing to license. Two compositions, picked by viewport shape, so
 * the stairway fills the screen on a phone and on a desktop alike. Both are
 * anchored to the top: the light sits near the top edge and the memorial card
 * starts below it (see .zb-theme-heavenly .zb-share-content in MemorialPage).
 *
 * Fixed behind the page content (the page sets `isolation: isolate`, so
 * z-index -1 sits above the page's own background colour but below its
 * children). Purely decorative: aria-hidden, no pointer events.
 */

const CSS = `
.zb-heavenly {
  position: fixed; inset: 0; z-index: -1; pointer-events: none;
  background-color: #fdeccb;
  background-image: url(${portrait});
  background-size: cover; background-position: center top; background-repeat: no-repeat;
}
@media (min-aspect-ratio: 1/1) {
  .zb-heavenly { background-image: url(${landscape}); }
}
`;

export default function HeavenlyBackdrop() {
  return (
    <>
      <style>{CSS}</style>
      <div className="zb-heavenly" aria-hidden="true" />
    </>
  );
}
